-- Архив миграции session 75: clp_generic_limits (GCL — пороги Annex I CLP)
-- Источник: .tmp-eurlex/clp-consolidated.html (02008R1272, консолидация 2026-05-01)
-- Применено через MCP: миграция clp_generic_limits_v1 (DDL) + insert.

-- session 75 · GCL — пороги Annex I CLP (generic cut-offs / concentration limits)
create table if not exists public.clp_generic_limits (
  rule_key            text primary key,
  kind                text not null check (kind in (
                        'CUTOFF','GCL','ELICITATION','SUMMATION','M_FACTOR',
                        'RELEVANT','SDS_TRIGGER','VARIATION','PH_RULE',
                        'UNKNOWN_INGREDIENT','SPECIAL')),
  class_code          text not null,           -- обобщённый код класса (ACUTE_TOX, SKIN_CORR_IRRIT, ED_HH …)
  catalog_codes       text[] not null default '{}', -- коды hazard_class_catalog для join
  ghs_chapter         text,                    -- раздел Annex I класса (3.2, 4.1 …)
  ingredient_category text,                    -- как классифицирован компонент (формулировка источника)
  result_category     text,                    -- во что классифицируется смесь
  physical_state      text not null default 'all' check (physical_state in ('all','solid/liquid','gas')),
  operator            text check (operator in ('>=','>','<','<=','>=..<','>..<=')),
  limit_low           numeric,                 -- нижняя граница (для '>=' — сам порог)
  limit_high          numeric,                 -- верхняя граница (для '<'/'<=' — сам порог)
  unit                text,                    -- '%', '% w/w', '% v/v', 'mg/l'
  weight_factor       numeric,                 -- множитель в аддитивной формуле (10, 100)
  value               numeric,                 -- вторичное число: M-фактор, ± % вариации, вязкость
  value_unit          text,
  formula_raw         text,                    -- левая колонка таблицы (сумма/формула) дословно
  raw                 text not null,           -- ячейка/предложение источника дословно
  source_ref          text not null,           -- 'Table 3.2.3' | '3.10.3.3.1.2'
  source_section      text,                    -- пункт, вводящий таблицу
  marker              text,                    -- маркер консолидации: B, M2, M4, M12, M19, M32
  note                text,
  needs_review        boolean not null default false,
  source              text not null default 'CLP 02008R1272 consolidated 2026-05-01, Annex I',
  created_at          timestamptz not null default now()
);
comment on table public.clp_generic_limits is
  'Annex I CLP: generic cut-off values (Table 1.1), generic concentration limits по классам, summation/M-factors (4.1), Table 1.2. Рукотворная таблица, числа только из консолидации 2026-05-01. Session 75.';
create index if not exists clp_generic_limits_class_idx on public.clp_generic_limits (class_code, kind);
create index if not exists clp_generic_limits_catalog_idx on public.clp_generic_limits using gin (catalog_codes);
alter table public.clp_generic_limits enable row level security;
drop policy if exists "public read" on public.clp_generic_limits;
create policy "public read" on public.clp_generic_limits for select using (true);

insert into public.clp_generic_limits (rule_key, kind, class_code, catalog_codes, ghs_chapter, ingredient_category, result_category, physical_state, operator, limit_low, limit_high, unit, weight_factor, value, value_unit, formula_raw, raw, source_ref, source_section, marker, note, needs_review) values
('T1.1-ACUTE_TOX-CAT1-3', 'CUTOFF', 'ACUTE_TOX', '{ACUTE_TOX_ORAL,ACUTE_TOX_DERMAL,ACUTE_TOX_INHAL}', '3.1', 'Acute Toxicity: — Category 1-3', null, 'all', '>=', 0.1, null, '%', null, null, null, null, '— Category 1-3 | 0,1 %', 'Table 1.1', '1.1.2.2.2', 'M19', 'Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-ACUTE_TOX-CAT4', 'CUTOFF', 'ACUTE_TOX', '{ACUTE_TOX_ORAL,ACUTE_TOX_DERMAL,ACUTE_TOX_INHAL}', '3.1', 'Acute Toxicity: — Category 4', null, 'all', '>=', 1, null, '%', null, null, null, null, '— Category 4 | 1 %', 'Table 1.1', '1.1.2.2.2', 'M19', 'Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-SKIN_CORR_IRRIT', 'CUTOFF', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Skin corrosion/Irritation', null, 'all', '>=', 1, null, '%', null, null, null, null, 'Skin corrosion/Irritation | 1 % (1)', 'Table 1.1', '1.1.2.2.2', 'M19', '(1) Or < 1 % where relevant, see 3.2.3.3.1. Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-EYE_DAMAGE_IRRIT', 'CUTOFF', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Serious damage to eyes/eye irritation', null, 'all', '>=', 1, null, '%', null, null, null, null, 'Serious damage to eyes/eye irritation | 1 % (2)', 'Table 1.1', '1.1.2.2.2', 'M19', '(2) Or < 1 % where relevant, see 3.3.3.3.1. Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-STOT_SE-CAT3', 'CUTOFF', 'STOT_SE', '{STOT_SE}', '3.8', 'Specific target organ toxicity, single exposure, Category 3', null, 'all', '>=', 1, null, '%', null, null, null, null, 'Specific target organ toxicity, single exposure, Category 3 | 1 % (3)', 'Table 1.1', '1.1.2.2.2', 'M19', '(3) Or < 1 % where relevant, see 3.8.3.4.6. Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-ASPIRATION', 'CUTOFF', 'ASPIRATION', '{ASPIRATION}', '3.10', 'Aspiration toxicity', null, 'all', '>=', 1, null, '%', null, null, null, null, 'Aspiration toxicity | 1 %', 'Table 1.1', '1.1.2.2.2', 'M19', 'Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-AQUATIC_ACUTE-1', 'CUTOFF', 'AQUATIC_ACUTE', '{AQUATIC_ACUTE}', '4.1', 'Hazardous to Aquatic Environment — Acute Category 1', null, 'all', '>=', 0.1, null, '%', null, null, null, null, '— Acute Category 1 | 0,1 % (4)', 'Table 1.1', '1.1.2.2.2', 'M19', '(4) Or < 0,1 % where relevant, see 4.1.3.1. Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-AQUATIC_CHRONIC-1', 'CUTOFF', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Hazardous to Aquatic Environment — Chronic Category 1', null, 'all', '>=', 0.1, null, '%', null, null, null, null, '— Chronic Category 1 | 0,1 % (4)', 'Table 1.1', '1.1.2.2.2', 'M19', '(4) Or < 0,1 % where relevant, see 4.1.3.1. Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.1-AQUATIC_CHRONIC-2-4', 'CUTOFF', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Hazardous to Aquatic Environment — Chronic Category 2-4', null, 'all', '>=', 1, null, '%', null, null, null, null, '— Chronic Category 2-4 | 1 %', 'Table 1.1', '1.1.2.2.2', 'M19', 'Note to Table 1.1 (▼M2): Generic cut-off values are in weight percentages except for gaseous mixtures for those hazard classes where the generic cut-off values may be best described in volume percentages.', false),
('T1.2-LE2.5', 'VARIATION', 'ANY', '{}', '1.1', 'Initial concentration range of the constituent: ≤ 2,5 %', null, 'all', '<=', null, 2.5, '%', null, 30, '± %', null, '≤ 2,5 % | ± 30 %', 'Table 1.2', '1.1.3.6', 'B', 'Bridging Principle for changes in the composition of a mixture (Article 15(2)(a)). Permitted variation in initial concentration of the constituent.', false),
('T1.2-2.5-10', 'VARIATION', 'ANY', '{}', '1.1', 'Initial concentration range of the constituent: 2,5 < C ≤ 10 %', null, 'all', '>..<=', 2.5, 10, '%', null, 20, '± %', null, '2,5 < C ≤ 10 % | ± 20 %', 'Table 1.2', '1.1.3.6', 'B', 'Bridging Principle for changes in the composition of a mixture (Article 15(2)(a)). Permitted variation in initial concentration of the constituent.', false),
('T1.2-10-25', 'VARIATION', 'ANY', '{}', '1.1', 'Initial concentration range of the constituent: 10 < C ≤ 25 %', null, 'all', '>..<=', 10, 25, '%', null, 10, '± %', null, '10 < C ≤ 25 % | ± 10 %', 'Table 1.2', '1.1.3.6', 'B', 'Bridging Principle for changes in the composition of a mixture (Article 15(2)(a)). Permitted variation in initial concentration of the constituent.', false),
('T1.2-25-100', 'VARIATION', 'ANY', '{}', '1.1', 'Initial concentration range of the constituent: 25 < C ≤ 100 %', null, 'all', '>..<=', 25, 100, '%', null, 5, '± %', null, '25 < C ≤ 100 % | ± 5 %', 'Table 1.2', '1.1.3.6', 'B', 'Bridging Principle for changes in the composition of a mixture (Article 15(2)(a)). Permitted variation in initial concentration of the constituent.', false),
('3.1.3.3a-RELEVANT', 'RELEVANT', 'ACUTE_TOX', '{ACUTE_TOX_ORAL,ACUTE_TOX_DERMAL,ACUTE_TOX_INHAL}', '3.1', 'any ingredient (acute toxicity)', null, 'all', '>=', 1, null, '% (w/w solids, liquids, dusts, mists, vapours; v/v gases)', null, null, null, null, 'the ‘relevant ingredients’ of a mixture are those which are present in concentrations of 1 % (w/w for solids, liquids, dusts, mists and vapours and v/v for gases) or greater, unless there is a reason to suspect that an ingredient present at a concentration of less than 1 % is still relevant for classifying the mixture for acute toxicity (see Table 1.1).', '3.1.3.3(a)', '3.1.3.3', 'B', null, false),
('3.1.3.6.2.2-UNKNOWN', 'UNKNOWN_INGREDIENT', 'ACUTE_TOX', '{ACUTE_TOX_ORAL,ACUTE_TOX_DERMAL,ACUTE_TOX_INHAL}', '3.1', 'component without any useable information', null, 'all', '>=', 1, null, '%', null, null, null, null, 'In the event that a component without any useable information for classification is used in a mixture at a concentration ≥ 1 %, it is concluded that the mixture cannot be attributed a definitive acute toxicity estimate. In this situation the mixture shall be classified based on the known components only, with the additional statement on the label and in the SDS that ‘x per cent of the mixture consists of component(s) of unknown acute toxicity’, taking into account the provisions set out in section 3.1.4.2.', '3.1.3.6.2.2', '3.1.3.6.2', 'M4', null, false),
('3.1.3.6.2.3-UNKNOWN-LE10', 'UNKNOWN_INGREDIENT', 'ACUTE_TOX', '{ACUTE_TOX_ORAL,ACUTE_TOX_DERMAL,ACUTE_TOX_INHAL}', '3.1', 'total of relevant ingredient(s) with unknown acute toxicity', null, 'all', '<=', null, 10, '%', null, null, null, null, 'If the total concentration of the relevant ingredient(s) with unknown acute toxicity is ≤ 10 % then the formula presented in section 3.1.3.6.1 shall be used.', '3.1.3.6.2.3', '3.1.3.6.2', 'M4', null, false),
('3.1.3.6.2.3-UNKNOWN-GT10', 'UNKNOWN_INGREDIENT', 'ACUTE_TOX', '{ACUTE_TOX_ORAL,ACUTE_TOX_DERMAL,ACUTE_TOX_INHAL}', '3.1', 'total of relevant ingredient(s) with unknown acute toxicity', null, 'all', '>', 10, null, '%', null, null, null, '(100 − Σ C_unknown) / ATE_mix = Σ (C_i / ATE_i)', 'If the total concentration of the relevant ingredient(s) with unknown toxicity is > 10 %, the formula presented in section 3.1.3.6.1 shall be corrected to adjust for the percentage of the unknown ingredient(s)', '3.1.3.6.2.3', '3.1.3.6.2', 'M4', 'Формула в источнике дана картинкой/формулой; в formula_raw — общепринятая запись скорректированной формулы 3.1.3.6.1, сверить с ate.ts.', true),
('T3.2.3-CORR-SUM-GE5', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1', 'Skin corrosion Category 1 (see note below)', 'all', '>=', 5, null, '%', null, null, null, 'Sum of Skin corrosion Sub-Category 1A, 1B, 1C or Category 1', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 | ≥ 5 % | ≥ 1 % but < 5 %', 'Table 3.2.3', '3.2.3.3.3', 'M12', 'Note: The sum of all ingredients of a mixture classified as Skin Corrosion Sub-Category 1A, 1B, or 1C respectively, shall each be ≥ 5 % in order to classify the mixture as either Skin Corrosion Sub-Category 1A, 1B or 1C. If the sum of the ingredients classified as Skin Corrosion Sub-Category 1A is < 5 % but the sum of ingredients classified as Skin Corrosion Sub-Category 1A + 1B is ≥ 5 %, the mixture shall be classified as Skin Corrosion Sub-Category 1B. Similarly, if the sum of ingredients classified as Skin Corrosion Sub-Category 1A + 1B ingredients is < 5 % but the sum of ingredients classified as Sub-Category 1A + 1B + 1C is ≥ 5 % the mixture shall be classified as Skin Corrosion Sub-Category 1C. Where at least one relevant ingredient in a mixture is classified as Category 1 without sub-categorisation, the mixture shall be classified as Category 1 without sub-categorisation if the sum of all ingredients corrosive to skin is ≥ 5 %.', false),
('T3.2.3-CORR-SUM-1-5', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1', 'Skin irritation Category 2', 'all', '>=..<', 1, 5, '%', null, null, null, 'Sum of Skin corrosion Sub-Category 1A, 1B, 1C or Category 1', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 | ≥ 5 % | ≥ 1 % but < 5 %', 'Table 3.2.3', '3.2.3.3.3', 'M12', null, false),
('T3.2.3-IRRIT-SUM-GE10', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Skin irritation Category 2', 'Skin irritation Category 2', 'all', '>=', 10, null, '%', null, null, null, 'Sum of Skin irritation Category 2', 'Skin irritation Category 2 | | ≥ 10 %', 'Table 3.2.3', '3.2.3.3.3', 'M12', null, false),
('T3.2.3-WEIGHTED-GE10', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', '(10 × Skin corrosion Sub-Category 1A, 1B, 1C or Category 1) + Skin irritation Category 2', 'Skin irritation Category 2', 'all', '>=', 10, null, '%', 10, null, null, '(10 × Skin corrosion Sub-Category 1A, 1B, 1C or Category 1) + Skin irritation Category 2', '(10 × Skin corrosion Sub-Category 1A, 1B, 1C or Category 1) + Skin irritation Category 2 | | ≥ 10 %', 'Table 3.2.3', '3.2.3.3.3', 'M12', null, false),
('T3.2.4-ACID', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Acid with pH ≤ 2', 'Skin corrosion Category 1', 'all', '>=', 1, null, '%', null, null, null, null, 'Acid with pH ≤ 2 | ≥ 1 % | Skin corrosion Category 1', 'Table 3.2.4', '3.2.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('T3.2.4-BASE', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Base with pH ≥ 11,5', 'Skin corrosion Category 1', 'all', '>=', 1, null, '%', null, null, null, null, 'Base with pH ≥ 11,5 | ≥ 1 % | Skin corrosion Category 1', 'Table 3.2.4', '3.2.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('T3.2.4-OTHER-CORR', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Other skin corrosive (Sub-Categories 1A, 1B, 1C or Category 1) ingredients', 'Skin corrosion Category 1', 'all', '>=', 1, null, '%', null, null, null, null, 'Other skin corrosive (Sub-Categories 1A, 1B, 1C or Category 1) ingredients | ≥ 1 % | Skin corrosion Category 1', 'Table 3.2.4', '3.2.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('T3.2.4-OTHER-IRRIT', 'GCL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'Other skin irritant (Category 2) ingredients, including acids and bases', 'Skin irritation Category 2', 'all', '>=', 3, null, '%', null, null, null, null, 'Other skin irritant (Category 2) ingredients, including acids and bases | ≥ 3 % | Skin irritation Category 2', 'Table 3.2.4', '3.2.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('3.2.3.1.2-PH', 'PH_RULE', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'mixture as a whole (pH)', 'Skin Corrosion Category 1', 'all', null, null, null, 'pH', null, null, null, 'pH ≤ 2 or pH ≥ 11,5', 'In the absence of any other information, a mixture is considered corrosive to skin (Skin Corrosion Category 1) if it has a pH ≤ 2 or a pH ≥ 11,5. However, if consideration of acid/alkaline reserve suggests the mixture may not be corrosive despite the low or high pH value, this needs to be confirmed by other data, preferably by data from an appropriate validated in vitro test.', '3.2.3.1.2', '3.2.3.1', 'M12', null, false),
('3.2.3.3.6-LOWER', 'SPECIAL', 'SKIN_CORR_IRRIT', '{SKIN_CORR_IRRIT}', '3.2', 'ingredient with data showing effect below GCL', null, 'all', '<', null, 1, '%', null, null, null, null, 'If there are data showing that (an) ingredient(s) is/are corrosive or irritant to skin at a concentration of < 1 % (skin corrosive) or < 3 % (skin irritant), the mixture shall be classified accordingly.', '3.2.3.3.6', '3.2.3.3', 'M12', '< 1 % skin corrosive; < 3 % skin irritant. Это ссылка сноски (1) Table 1.1.', false),
('T3.3.3-CORR+DAM-SUM-GE3', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 + Serious eye damage (Category 1) (1)', 'Serious eye damage Category 1', 'all', '>=', 3, null, '%', null, null, null, 'Sum of Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 + Serious eye damage (Category 1)', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 + Serious eye damage (Category 1) ( ) | ≥ 3 % | ≥ 1 % but < 3 %', 'Table 3.3.3', '3.3.3.3.3', 'M12', '(1) If an ingredient is classified as both Skin Corrosion Sub-Category 1A, 1B, 1C or Category 1 and Serious Eye Damage (Category 1), its concentration is considered only once in the calculation.', false),
('T3.3.3-CORR+DAM-SUM-1-3', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 + Serious eye damage (Category 1) (1)', 'Eye irritation Category 2', 'all', '>=..<', 1, 3, '%', null, null, null, 'Sum of Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 + Serious eye damage (Category 1)', 'Skin corrosion Sub-Category 1A, 1B, 1C or Category 1 + Serious eye damage (Category 1) ( ) | ≥ 3 % | ≥ 1 % but < 3 %', 'Table 3.3.3', '3.3.3.3.3', 'M12', '(1) If an ingredient is classified as both Skin Corrosion Sub-Category 1A, 1B, 1C or Category 1 and Serious Eye Damage (Category 1), its concentration is considered only once in the calculation.', false),
('T3.3.3-IRRIT-SUM-GE10', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Eye irritation (Category 2)', 'Eye irritation Category 2', 'all', '>=', 10, null, '%', null, null, null, 'Sum of Eye irritation (Category 2)', 'Eye irritation (Category 2) | | ≥ 10 %', 'Table 3.3.3', '3.3.3.3.3', 'M12', null, false),
('T3.3.3-WEIGHTED-GE10', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', '10 × (Skin corrosion Sub-Category 1A, 1B, 1C or Skin corrosion Category 1 + Serious eye damage (Category 1)) + Eye irritation (Category 2)', 'Eye irritation Category 2', 'all', '>=', 10, null, '%', 10, null, null, '10 × (Skin corrosion Sub-Category 1A, 1B, 1C or Skin corrosion Category 1 + Serious eye damage (Category 1)) + Eye irritation (Category 2)', '10 × (Skin corrosion Sub-Category 1A, 1B, 1C or Skin corrosion Category 1 + Serious eye damage (Category 1)) + Eye irritation (Category 2) | | ≥ 10 %', 'Table 3.3.3', '3.3.3.3.3', 'M12', null, false),
('T3.3.4-ACID', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Acid with pH ≤ 2', 'Serious eye damage (Category 1)', 'all', '>=', 1, null, '%', null, null, null, null, 'Acid with pH ≤ 2 | ≥ 1 % | Serious eye damage (Category 1)', 'Table 3.3.4', '3.3.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('T3.3.4-BASE', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Base with pH ≥ 11,5', 'Serious eye damage (Category 1)', 'all', '>=', 1, null, '%', null, null, null, null, 'Base with pH ≥ 11,5 | ≥ 1 % | Serious eye damage (Category 1)', 'Table 3.3.4', '3.3.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('T3.3.4-OTHER-CORR-DAM', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Other ingredient classified as skin corrosion (Sub-Category 1A, 1B, 1C or Category 1) or serious eye damage (Category 1)', 'Serious eye damage (Category 1)', 'all', '>=', 1, null, '%', null, null, null, null, 'Other ingredient classified as skin corrosion (Sub-Category 1A, 1B, 1C or Category 1) or serious eye damage (Category 1) | ≥ 1 % | Serious eye damage (Category 1)', 'Table 3.3.4', '3.3.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('T3.3.4-OTHER-IRRIT', 'GCL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'Other ingredient classified as eye irritation (Category 2)', 'Eye irritation (Category 2)', 'all', '>=', 3, null, '%', null, null, null, null, 'Other ingredient classified as eye irritation (Category 2) | ≥ 3 % | Eye irritation (Category 2)', 'Table 3.3.4', '3.3.3.3.4.3', 'M12', 'additivity approach does not apply', false),
('3.3.3.1.2-PH', 'PH_RULE', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'mixture as a whole (pH)', 'Serious eye damage (Category 1)', 'all', null, null, null, 'pH', null, null, null, 'pH ≤ 2 or pH ≥ 11,5', 'In the absence of any other information, a mixture is considered to cause serious eye damage (Category 1) if it has a pH ≤ 2 or ≥ 11,5. However, if consideration of acid/alkali reserve suggests the mixture may not cause serious eye damage despite the low or high pH value, this needs to be confirmed by other data, preferably data from an appropriate validated in vitro test.', '3.3.3.1.2', '3.3.3.1', 'M12', null, false),
('3.3.3.3.6-LOWER', 'SPECIAL', 'EYE_DAMAGE_IRRIT', '{EYE_DAMAGE_IRRIT}', '3.3', 'ingredient with data showing effect below GCL', null, 'all', '<', null, 1, '%', null, null, null, null, 'If there are data showing that (an) ingredient(s) may be corrosive to the skin or seriously damaging to the eye/eye irritating at a concentration of < 1 % (corrosive to the skin or seriously damaging to the eye) or < 3 % (eye irritant), the mixture shall be classified accordingly.', '3.3.3.3.6', '3.3.3.3', 'M12', '< 1 % corrosive/serious eye damage; < 3 % eye irritant. Это ссылка сноски (2) Table 1.1.', false),
('T3.4.5-RESP1-SL', 'GCL', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Category 1', 'Respiratory sensitiser Category 1', 'solid/liquid', '>=', 1.0, null, '%', null, null, null, null, 'Respiratory sensitiser Category 1 | ≥ 1,0 % | ≥ 0,2 % |', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-RESP1-SL', 'ELICITATION', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Category 1', 'Respiratory sensitiser Category 1 (elicitation; Annex II 2.8)', 'solid/liquid', '>=', 0.1, null, '%', null, null, null, null, 'Respiratory sensitiser Category 1 | ≥ 0,1 % (Note 1) | ≥ 0,1 % (Note 1) |', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-RESP1-GAS', 'GCL', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Category 1', 'Respiratory sensitiser Category 1', 'gas', '>=', 0.2, null, '%', null, null, null, null, 'Respiratory sensitiser Category 1 | ≥ 1,0 % | ≥ 0,2 % |', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-RESP1-GAS', 'ELICITATION', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Category 1', 'Respiratory sensitiser Category 1 (elicitation; Annex II 2.8)', 'gas', '>=', 0.1, null, '%', null, null, null, null, 'Respiratory sensitiser Category 1 | ≥ 0,1 % (Note 1) | ≥ 0,1 % (Note 1) |', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-RESP1A-SL', 'GCL', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1A', 'Respiratory sensitiser Category 1', 'solid/liquid', '>=', 0.1, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1A | ≥ 0,1 % | ≥ 0,1 % |', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-RESP1A-SL', 'ELICITATION', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1A', 'Respiratory sensitiser Category 1 (elicitation; Annex II 2.8)', 'solid/liquid', '>=', 0.01, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1A | ≥ 0,01 % (Note 1) | ≥ 0,01 % (Note 1) |', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-RESP1A-GAS', 'GCL', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1A', 'Respiratory sensitiser Category 1', 'gas', '>=', 0.1, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1A | ≥ 0,1 % | ≥ 0,1 % |', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-RESP1A-GAS', 'ELICITATION', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1A', 'Respiratory sensitiser Category 1 (elicitation; Annex II 2.8)', 'gas', '>=', 0.01, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1A | ≥ 0,01 % (Note 1) | ≥ 0,01 % (Note 1) |', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-RESP1B-SL', 'GCL', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1B', 'Respiratory sensitiser Category 1', 'solid/liquid', '>=', 1.0, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1B | ≥ 1,0 % | ≥ 0,2 % |', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-RESP1B-SL', 'ELICITATION', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1B', 'Respiratory sensitiser Category 1 (elicitation; Annex II 2.8)', 'solid/liquid', '>=', 0.1, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1B | ≥ 0,1 % (Note 1) | ≥ 0,1 % (Note 1) |', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-RESP1B-GAS', 'GCL', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1B', 'Respiratory sensitiser Category 1', 'gas', '>=', 0.2, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1B | ≥ 1,0 % | ≥ 0,2 % |', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-RESP1B-GAS', 'ELICITATION', 'RESP_SENS', '{RESP_SENS}', '3.4', 'Respiratory sensitiser Sub-category 1B', 'Respiratory sensitiser Category 1 (elicitation; Annex II 2.8)', 'gas', '>=', 0.1, null, '%', null, null, null, null, 'Respiratory sensitiser Sub-category 1B | ≥ 0,1 % (Note 1) | ≥ 0,1 % (Note 1) |', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-SKIN1', 'GCL', 'SKIN_SENS', '{SKIN_SENS}', '3.4', 'Skin sensitiser Category 1', 'Skin sensitiser Category 1', 'all', '>=', 1.0, null, '%', null, null, null, null, 'Skin sensitiser Category 1 | | | ≥ 1,0 %', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-SKIN1', 'ELICITATION', 'SKIN_SENS', '{SKIN_SENS}', '3.4', 'Skin sensitiser Category 1', 'Skin sensitiser Category 1 (elicitation; Annex II 2.8)', 'all', '>=', 0.1, null, '%', null, null, null, null, 'Skin sensitiser Category 1 | | | ≥ 0,1 % (Note 1)', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-SKIN1A', 'GCL', 'SKIN_SENS', '{SKIN_SENS}', '3.4', 'Skin sensitiser Sub-category 1A', 'Skin sensitiser Category 1', 'all', '>=', 0.1, null, '%', null, null, null, null, 'Skin sensitiser Sub-category 1A | | | ≥ 0,1 %', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-SKIN1A', 'ELICITATION', 'SKIN_SENS', '{SKIN_SENS}', '3.4', 'Skin sensitiser Sub-category 1A', 'Skin sensitiser Category 1 (elicitation; Annex II 2.8)', 'all', '>=', 0.01, null, '%', null, null, null, null, 'Skin sensitiser Sub-category 1A | | | ≥ 0,01 % (Note 1)', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.4.5-SKIN1B', 'GCL', 'SKIN_SENS', '{SKIN_SENS}', '3.4', 'Skin sensitiser Sub-category 1B', 'Skin sensitiser Category 1', 'all', '>=', 1.0, null, '%', null, null, null, null, 'Skin sensitiser Sub-category 1B | | | ≥ 1,0 %', 'Table 3.4.5', '3.4.3.3.1', 'M2', 'columns: Solid/liquid | Gas | All physical states', false),
('T3.4.6-SKIN1B', 'ELICITATION', 'SKIN_SENS', '{SKIN_SENS}', '3.4', 'Skin sensitiser Sub-category 1B', 'Skin sensitiser Category 1 (elicitation; Annex II 2.8)', 'all', '>=', 0.1, null, '%', null, null, null, null, 'Skin sensitiser Sub-category 1B | | | ≥ 0,1 % (Note 1)', 'Table 3.4.6', '3.4.3.3.2', 'M2', 'Note 1 (▼M19): This concentration limit for elicitation is used for the application of the special labelling requirements of section 2.8 of Annex II to protect already sensitised individuals. A SDS is required for the mixture containing a component at or above this concentration. For sensitising substances with a specific concentration limit, the concentration limit for elicitation shall be set at a tenth of the specific concentration limit.', false),
('T3.5.2-1A', 'GCL', 'MUTAGEN', '{MUTAGEN}', '3.5', 'Category 1A mutagen', 'Category 1 mutagen — Category 1A', 'all', '>=', 0.1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1A mutagen | ≥ 0,1 % | — | —', 'Table 3.5.2', '3.5.3.1.1', 'M4', 'Note: The concentration limits in the table above apply to solids and liquids (w/w units) as well as gases (v/v units).', false),
('T3.5.2-1B', 'GCL', 'MUTAGEN', '{MUTAGEN}', '3.5', 'Category 1B mutagen', 'Category 1 mutagen — Category 1B', 'all', '>=', 0.1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1B mutagen | — | ≥ 0,1 % | —', 'Table 3.5.2', '3.5.3.1.1', 'M4', 'Note: The concentration limits in the table above apply to solids and liquids (w/w units) as well as gases (v/v units).', false),
('T3.5.2-2', 'GCL', 'MUTAGEN', '{MUTAGEN}', '3.5', 'Category 2 mutagen', 'Category 2 mutagen', 'all', '>=', 1.0, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 2 mutagen | — | — | ≥ 1,0 %', 'Table 3.5.2', '3.5.3.1.1', 'M4', 'Note: The concentration limits in the table above apply to solids and liquids (w/w units) as well as gases (v/v units).', false),
('T3.6.2-1A', 'GCL', 'CARCINOGEN', '{CARCINOGEN}', '3.6', 'Category 1A carcinogen', 'Category 1 carcinogen — Category 1A', 'all', '>=', 0.1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1A carcinogen | ≥ 0,1 % | — | —', 'Table 3.6.2', '3.6.3.1.1', 'M4', 'Note: The concentration limits in the table above apply to solids and liquids (w/w units) as well as gases (v/v units).', false),
('T3.6.2-1B', 'GCL', 'CARCINOGEN', '{CARCINOGEN}', '3.6', 'Category 1B carcinogen', 'Category 1 carcinogen — Category 1B', 'all', '>=', 0.1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1B carcinogen | — | ≥ 0,1 % | —', 'Table 3.6.2', '3.6.3.1.1', 'M4', 'Note: The concentration limits in the table above apply to solids and liquids (w/w units) as well as gases (v/v units).', false),
('T3.6.2-2', 'GCL', 'CARCINOGEN', '{CARCINOGEN}', '3.6', 'Category 2 carcinogen', 'Category 2 carcinogen', 'all', '>=', 1.0, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 2 carcinogen | — | — | ≥ 1,0 % [Note 1]', 'Table 3.6.2', '3.6.3.1.1', 'M4', 'Note: The concentration limits in the table above apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 2 carcinogen is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request.', false),
('T3.6.2-2-SDS', 'SDS_TRIGGER', 'CARCINOGEN', '{CARCINOGEN}', '3.6', 'Category 2 carcinogen', 'SDS available upon request', 'all', '>=', 0.1, null, '%', null, null, null, null, 'If a Category 2 carcinogen is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request.', 'Table 3.6.2 Note 1', '3.6.3.1.1', 'B', null, false),
('T3.7.2-1A', 'GCL', 'REPRO_TOX', '{REPRO_TOX}', '3.7', 'Category 1A reproductive toxicant', 'Category 1 reproductive toxicant — Category 1A', 'all', '>=', 0.3, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1A reproductive toxicant | ≥ 0,3 % [Note 1] | | |', 'Table 3.7.2', '3.7.3.1.1', 'M4', 'Note: The concentration limits in Table 3.7.2 apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 1 or Category 2 reproductive toxicant or a substance classified for effects on or via lactation is present in the mixture as an ingredient at a concentration at or above 0,1 %, a SDS shall be available for the mixture upon request.', false),
('T3.7.2-1B', 'GCL', 'REPRO_TOX', '{REPRO_TOX}', '3.7', 'Category 1B reproductive toxicant', 'Category 1 reproductive toxicant — Category 1B', 'all', '>=', 0.3, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1B reproductive toxicant | | ≥ 0,3 % [Note 1] | |', 'Table 3.7.2', '3.7.3.1.1', 'M4', 'Note: The concentration limits in Table 3.7.2 apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 1 or Category 2 reproductive toxicant or a substance classified for effects on or via lactation is present in the mixture as an ingredient at a concentration at or above 0,1 %, a SDS shall be available for the mixture upon request.', false),
('T3.7.2-2', 'GCL', 'REPRO_TOX', '{REPRO_TOX}', '3.7', 'Category 2 reproductive toxicant', 'Category 2 reproductive toxicant', 'all', '>=', 3.0, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 2 reproductive toxicant | | | ≥ 3,0 % [Note 1] |', 'Table 3.7.2', '3.7.3.1.1', 'M4', 'Note: The concentration limits in Table 3.7.2 apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 1 or Category 2 reproductive toxicant or a substance classified for effects on or via lactation is present in the mixture as an ingredient at a concentration at or above 0,1 %, a SDS shall be available for the mixture upon request.', false),
('T3.7.2-LACT', 'GCL', 'REPRO_TOX', '{REPRO_TOX}', '3.7', 'Additional category for effects on or via lactation', 'Additional category for effects on or via lactation', 'all', '>=', 0.3, null, '% (w/w; v/v gases)', null, null, null, null, 'Additional category for effects on or via lactation | | | | ≥ 0,3 % [Note 1]', 'Table 3.7.2', '3.7.3.1.1', 'M4', 'Note: The concentration limits in Table 3.7.2 apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 1 or Category 2 reproductive toxicant or a substance classified for effects on or via lactation is present in the mixture as an ingredient at a concentration at or above 0,1 %, a SDS shall be available for the mixture upon request.', false),
('T3.7.2-SDS', 'SDS_TRIGGER', 'REPRO_TOX', '{REPRO_TOX}', '3.7', 'Category 1 or Category 2 reproductive toxicant or a substance classified for effects on or via lactation', 'SDS available upon request', 'all', '>=', 0.1, null, '%', null, null, null, null, 'Note 1: If a Category 1 or Category 2 reproductive toxicant or a substance classified for effects on or via lactation is present in the mixture as an ingredient at a concentration at or above 0,1 %, a SDS shall be available for the mixture upon request.', 'Table 3.7.2 Note 1', '3.7.3.1.1', 'M4', null, false),
('T3.8.3-1-GE10', 'GCL', 'STOT_SE', '{STOT_SE}', '3.8', 'Category 1 Specific Target Organ Toxicant', 'Category 1', 'all', '>=', 10, null, '%', null, null, null, null, 'Category 1 Specific Target Organ Toxicant | Concentration ≥ 10 % | 1,0 % ≤ concentration < 10 %', 'Table 3.8.3', '3.8.3.4.1', 'B', null, false),
('T3.8.3-1-1-10', 'GCL', 'STOT_SE', '{STOT_SE}', '3.8', 'Category 1 Specific Target Organ Toxicant', 'Category 2', 'all', '>=..<', 1.0, 10, '%', null, null, null, null, 'Category 1 Specific Target Organ Toxicant | Concentration ≥ 10 % | 1,0 % ≤ concentration < 10 %', 'Table 3.8.3', '3.8.3.4.1', 'B', null, false),
('T3.8.3-2-GE10', 'GCL', 'STOT_SE', '{STOT_SE}', '3.8', 'Category 2 Specific Target Organ Toxicant', 'Category 2', 'all', '>=', 10, null, '%', null, null, null, null, 'Category 2 Specific Target Organ Toxicant | | Concentration ≥ 10 % [(Note 1)]', 'Table 3.8.3', '3.8.3.4.1', 'B', 'Note 1: If a Category 2 specific target organ toxicant is present in the mixture as an ingredient at a concentration ≥ 1,0 % a SDS shall be available for the mixture upon request.', false),
('T3.8.3-2-SDS', 'SDS_TRIGGER', 'STOT_SE', '{STOT_SE}', '3.8', 'Category 2 Specific Target Organ Toxicant', 'SDS available upon request', 'all', '>=', 1.0, null, '%', null, null, null, null, 'If a Category 2 specific target organ toxicant is present in the mixture as an ingredient at a concentration ≥ 1,0 % a SDS shall be available for the mixture upon request.', 'Table 3.8.3 Note 1', '3.8.3.4.1', 'B', null, false),
('3.8.3.4.5-CAT3-GCL20', 'GCL', 'STOT_SE', '{STOT_SE}', '3.8', 'Category 3 ingredient(s) (respiratory tract irritation / narcotic effects)', 'Category 3', 'all', '>=', 20, null, '%', null, null, null, null, 'Care shall be exercised when extrapolating toxicity of a mixture that contains Category 3 ingredient(s). A generic concentration limit of 20 % is appropriate; however, it shall be recognised that this concentration limit may be higher or lower depending on the Category 3 ingredient(s) and that some effects such as respiratory tract irritation may not occur below a certain concentration while other effects such as narcotic effects may occur below this 20 % value. Expert judgement shall be exercised. Respiratory tract irritation and narcotic effects are to be evaluated separately in accordance with the criteria given in section 3.8.2.2. When conducting classifications for these hazards, the contribution of each component should be considered additive, unless there is evidence that the effects are not additive.', '3.8.3.4.5', '3.8.3.4', 'B', '«appropriate», не жёсткий порог: expert judgement; RTI и наркотические эффекты считать раздельно, вклад аддитивный (▼M2).', false),
('3.8.3.4.6-CAT3-RELEVANT', 'RELEVANT', 'STOT_SE', '{STOT_SE}', '3.8', 'Category 3 ingredients (additivity approach)', null, 'all', '>=', 1, null, '% (w/w solids, liquids, dusts, mists, vapours; v/v gases)', null, null, null, null, 'In cases where the additivity approach is used for Category 3 ingredients, the ‘relevant ingredients’ of a mixture are those which are present in concentrations ≥ 1 % (w/w for solids, liquids, dusts, mists, and vapours and v/v for gases), unless there is a reason to suspect that an ingredient present at a concentration < 1 % is still relevant when classifying the mixture for respiratory tract irritation or narcotic effects.', '3.8.3.4.6', '3.8.3.4', 'M19', 'Это ссылка сноски (3) Table 1.1.', false),
('T3.9.4-1-GE10', 'GCL', 'STOT_RE', '{STOT_RE}', '3.9', 'Category 1 Specific Target Organ Toxicant', 'Category 1', 'all', '>=', 10, null, '%', null, null, null, null, 'Category 1 Specific Target Organ Toxicant | Concentration ≥ 10 % | 1,0 % ≤ concentration < 10 %', 'Table 3.9.4', '3.9.3.4.1', 'B', null, false),
('T3.9.4-1-1-10', 'GCL', 'STOT_RE', '{STOT_RE}', '3.9', 'Category 1 Specific Target Organ Toxicant', 'Category 2', 'all', '>=..<', 1.0, 10, '%', null, null, null, null, 'Category 1 Specific Target Organ Toxicant | Concentration ≥ 10 % | 1,0 % ≤ concentration < 10 %', 'Table 3.9.4', '3.9.3.4.1', 'B', null, false),
('T3.9.4-2-GE10', 'GCL', 'STOT_RE', '{STOT_RE}', '3.9', 'Category 2 Specific Target Organ Toxicant', 'Category 2', 'all', '>=', 10, null, '%', null, null, null, null, 'Category 2 Specific Target Organ Toxicant | | Concentration ≥ 10 % [(Note 1)]', 'Table 3.9.4', '3.9.3.4.1', 'B', 'Note 1: If a Category 2 specific target organ toxicant is present in the mixture as an ingredient at a concentration ≥ 1,0 % a SDS shall be available for the mixture upon request.', false),
('T3.9.4-2-SDS', 'SDS_TRIGGER', 'STOT_RE', '{STOT_RE}', '3.9', 'Category 2 Specific Target Organ Toxicant', 'SDS available upon request', 'all', '>=', 1.0, null, '%', null, null, null, null, 'If a Category 2 specific target organ toxicant is present in the mixture as an ingredient at a concentration ≥ 1,0 % a SDS shall be available for the mixture upon request.', 'Table 3.9.4 Note 1', '3.9.3.4.1', 'B', null, false),
('3.10.3.3.1.1-RELEVANT', 'RELEVANT', 'ASPIRATION', '{ASPIRATION}', '3.10', 'any ingredient (aspiration)', null, 'all', '>=', 1, null, '%', null, null, null, null, 'The ‘relevant ingredients’ of a mixture are those which are present in concentrations ≥ 1 %.', '3.10.3.3.1.1', '3.10.3.3.1', 'M19', null, false),
('3.10.3.3.1.2-CAT1', 'GCL', 'ASPIRATION', '{ASPIRATION}', '3.10', 'Category 1 ingredients', 'Category 1', 'all', '>=', 10, null, '%', null, 20.5, 'mm2/s at 40 °C (kinematic viscosity, ≤)', 'Sum of Category 1 ingredients', 'A mixture is classified as Category 1 when the sum of the concentrations of Category 1 ingredients is ≥ 10 % and the mixture has a kinematic viscosity ≤ 20,5 mm2/s, measured at 40 °C.', '3.10.3.3.1.2', '3.10.3.3.1', 'M19', null, false),
('3.10.3.3.1.3-LAYERS', 'GCL', 'ASPIRATION', '{ASPIRATION}', '3.10', 'Category 1 ingredients in any distinct layer', 'Category 1 (entire mixture)', 'all', '>=', 10, null, '%', null, 20.5, 'mm2/s at 40 °C (kinematic viscosity, ≤)', 'Sum of Category 1 ingredients in any distinct layer', 'In the case of a mixture which separates into two or more distinct layers, the entire mixture is classified as Category 1 if in any distinct layer the sum of the concentrations of Category 1 ingredients is ≥ 10 %, and it has a kinematic viscosity ≤ 20,5 mm2/s, measured at 40 °C.', '3.10.3.3.1.3', '3.10.3.3.1', 'M19', null, false),
('3.10.3.2.1-DILUTION', 'SPECIAL', 'ASPIRATION', '{ASPIRATION}', '3.10', 'aspiration toxicant(s) (dilution bridging principle)', null, 'all', '>=', 10, null, '%', null, null, null, null, 'However, in the case of application of the dilution bridging principle, the concentration of aspiration toxicant(s) shall be 10 % or more.', '3.10.3.2.1', '3.10.3.2', 'B', null, false),
('T3.11.2-1', 'GCL', 'ED_HH', '{}', '3.11', 'Category 1 endocrine disruptor for human health', 'Category 1 endocrine disruptor for human health', 'all', '>=', 0.1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1 endocrine disruptor for human health | ≥ 0,1 % |', 'Table 3.11.2', '3.11.3.1.1', 'M32', 'Note: The concentration limits in this Table shall apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 2 endocrine disruptor for human health is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request. Application in time (3.11.3.4): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Sections 3.11.3.1, 3.11.3.2 and 3.11.3.3. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Sections 3.11.3.1, 3.11.3.2 and 3.11.3.3 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('T3.11.2-2', 'GCL', 'ED_HH', '{}', '3.11', 'Category 2 endocrine disruptor for human health', 'Category 2 endocrine disruptor for human health', 'all', '>=', 1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 2 endocrine disruptor for human health | | ≥ 1 % [Note 1]', 'Table 3.11.2', '3.11.3.1.1', 'M32', 'Note: The concentration limits in this Table shall apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 2 endocrine disruptor for human health is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request. Application in time (3.11.3.4): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Sections 3.11.3.1, 3.11.3.2 and 3.11.3.3. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Sections 3.11.3.1, 3.11.3.2 and 3.11.3.3 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('T3.11.2-2-SDS', 'SDS_TRIGGER', 'ED_HH', '{}', '3.11', 'Category 2 endocrine disruptor for human health', 'SDS available upon request', 'all', '>=', 0.1, null, '%', null, null, null, null, 'Note 1: If a Category 2 endocrine disruptor for human health is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request.', 'Table 3.11.2 Note 1', '3.11.3.1.1', 'M32', null, false),
('4.1.3.1-RELEVANT-A1C1', 'RELEVANT', 'AQUATIC', '{AQUATIC_ACUTE,AQUATIC_CHRONIC}', '4.1', '‘Acute 1’ or ‘Chronic 1’', null, 'all', '>=', 0.1, null, '% w/w', null, null, null, null, 'The ‘relevant components’ of a mixture are those which are classified ‘Acute 1’or ‘Chronic 1’ and present in a concentration of 0,1 % (w/w) or greater, and those which are classified ‘Chronic 2’, ‘Chronic 3’ or ‘Chronic 4’ and present in a concentration of 1 % (w/w) or greater, unless there is a presumption (such as in the case of highly toxic components (see section 4.1.3.5.5.5)) that a component present in a lower concentration can still be relevant for classifying the mixture for aquatic environmental hazards.', '4.1.3.1', '4.1.3.1', 'M2', 'Это ссылка сноски (4) Table 1.1.', false),
('4.1.3.1-RELEVANT-C2-4', 'RELEVANT', 'AQUATIC', '{AQUATIC_CHRONIC}', '4.1', '‘Chronic 2’, ‘Chronic 3’ or ‘Chronic 4’', null, 'all', '>=', 1, null, '% w/w', null, null, null, null, 'The ‘relevant components’ of a mixture are those which are classified ‘Acute 1’or ‘Chronic 1’ and present in a concentration of 0,1 % (w/w) or greater, and those which are classified ‘Chronic 2’, ‘Chronic 3’ or ‘Chronic 4’ and present in a concentration of 1 % (w/w) or greater, unless there is a presumption (such as in the case of highly toxic components (see section 4.1.3.5.5.5)) that a component present in a lower concentration can still be relevant for classifying the mixture for aquatic environmental hazards.', '4.1.3.1', '4.1.3.1', 'M2', null, false),
('T4.1.1-ACUTE1', 'SUMMATION', 'AQUATIC_ACUTE', '{AQUATIC_ACUTE}', '4.1', 'Acute 1 × M', 'Acute 1', 'all', '>=', 25, null, '%', null, null, null, 'Σ(Acute 1 × M)', 'Acute 1 × M (1) ≥ 25 % | Acute 1', 'Table 4.1.1', '4.1.3.5.5.3.2', 'M2', '(1) For explanation of the M-factor, see 4.1.3.5.5.5. Title ▼M12, content ▼M2.', false),
('T4.1.2-CHRONIC1', 'SUMMATION', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 × M', 'Chronic 1', 'all', '>=', 25, null, '%', null, null, null, 'Σ(Chronic 1 × M)', 'Chronic 1 × M (1) ≥ 25 % | Chronic 1', 'Table 4.1.2', '4.1.3.5.5.4.5', 'M2', '(1) For explanation of the M-factor, see 4.1.3.5.5.5. Title ▼M12, content ▼M2. Tiered: more severe classification overrides (4.1.3.5.5.2.1).', false),
('T4.1.2-CHRONIC2', 'SUMMATION', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', '(M × 10 × Chronic 1) + Chronic 2', 'Chronic 2', 'all', '>=', 25, null, '%', 10, null, null, '(M × 10 × Σ Chronic 1) + Σ Chronic 2', '(M × 10 × Chronic 1) + Chronic 2 ≥ 25 % | Chronic 2', 'Table 4.1.2', '4.1.3.5.5.4.5', 'M2', '(1) For explanation of the M-factor, see 4.1.3.5.5.5. Title ▼M12, content ▼M2. Tiered: more severe classification overrides (4.1.3.5.5.2.1).', false),
('T4.1.2-CHRONIC3', 'SUMMATION', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', '(M × 100 × Chronic 1) + (10 × Chronic 2) + Chronic 3', 'Chronic 3', 'all', '>=', 25, null, '%', 100, null, null, '(M × 100 × Σ Chronic 1) + (10 × Σ Chronic 2) + Σ Chronic 3', '(M × 100 × Chronic 1) + (10 × Chronic 2) + Chronic 3 ≥ 25 % | Chronic 3', 'Table 4.1.2', '4.1.3.5.5.4.5', 'M2', '(1) For explanation of the M-factor, see 4.1.3.5.5.5. Title ▼M12, content ▼M2. Tiered: more severe classification overrides (4.1.3.5.5.2.1). weight_factor=100 для Chronic 1; для Chronic 2 — 10.', false),
('T4.1.2-CHRONIC4', 'SUMMATION', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 + Chronic 2 + Chronic 3 + Chronic 4', 'Chronic 4', 'all', '>=', 25, null, '%', null, null, null, 'Σ Chronic 1 + Σ Chronic 2 + Σ Chronic 3 + Σ Chronic 4', 'Chronic 1 + Chronic 2 + Chronic 3 + Chronic 4 ≥ 25 % | Chronic 4', 'Table 4.1.2', '4.1.3.5.5.4.5', 'M2', '(1) For explanation of the M-factor, see 4.1.3.5.5.5. Title ▼M12, content ▼M2. Tiered: more severe classification overrides (4.1.3.5.5.2.1).', false),
('T4.1.3-ACUTE-B1', 'M_FACTOR', 'AQUATIC_ACUTE', '{AQUATIC_ACUTE}', '4.1', 'Acute 1 component: L(E)C50 value (mg/l)', 'M factor (acute)', 'all', '>..<=', 0.1, 1, 'mg/l', null, 1, 'M factor', null, '0,1 < L(E)C 50 ≤ 1 | 1 | 0,01 < NOEC ≤ 0,1 | 1 | —', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-ACUTE-B2', 'M_FACTOR', 'AQUATIC_ACUTE', '{AQUATIC_ACUTE}', '4.1', 'Acute 1 component: L(E)C50 value (mg/l)', 'M factor (acute)', 'all', '>..<=', 0.01, 0.1, 'mg/l', null, 10, 'M factor', null, '0,01 < L(E)C 50 ≤ 0,1 | 10 | 0,001 < NOEC ≤ 0,01 | 10 | 1', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-ACUTE-B3', 'M_FACTOR', 'AQUATIC_ACUTE', '{AQUATIC_ACUTE}', '4.1', 'Acute 1 component: L(E)C50 value (mg/l)', 'M factor (acute)', 'all', '>..<=', 0.001, 0.01, 'mg/l', null, 100, 'M factor', null, '0,001 < L(E)C 50 ≤ 0,01 | 100 | 0,0001 < NOEC ≤ 0,001 | 100 | 10', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-ACUTE-B4', 'M_FACTOR', 'AQUATIC_ACUTE', '{AQUATIC_ACUTE}', '4.1', 'Acute 1 component: L(E)C50 value (mg/l)', 'M factor (acute)', 'all', '>..<=', 0.0001, 0.001, 'mg/l', null, 1000, 'M factor', null, '0,0001 < L(E)C 50 ≤ 0,001 | 1 000 | 0,00001 < NOEC ≤ 0,0001 | 1 000 | 100', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-ACUTE-B5', 'M_FACTOR', 'AQUATIC_ACUTE', '{AQUATIC_ACUTE}', '4.1', 'Acute 1 component: L(E)C50 value (mg/l)', 'M factor (acute)', 'all', '>..<=', 1e-05, 0.0001, 'mg/l', null, 10000, 'M factor', null, '0,00001 < L(E)C 50 ≤ 0,0001 | 10 000 | 0,000001 < NOEC ≤ 0,00001 | 10 000 | 1 000', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-NRD-B1', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, NRD (non-rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, NRD)', 'all', '>..<=', 0.01, 0.1, 'mg/l', null, 1, 'M factor', null, '0,1 < L(E)C 50 ≤ 1 | 1 | 0,01 < NOEC ≤ 0,1 | 1 | —', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-RD-B1', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, RD (rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, RD)', 'all', '>..<=', 0.01, 0.1, 'mg/l', null, null, 'M factor', null, '0,1 < L(E)C 50 ≤ 1 | 1 | 0,01 < NOEC ≤ 0,1 | 1 | —', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals) В источнике «—»: M-фактор для RD в этой полосе не задан.', false),
('T4.1.3-CHRONIC-NRD-B2', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, NRD (non-rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, NRD)', 'all', '>..<=', 0.001, 0.01, 'mg/l', null, 10, 'M factor', null, '0,01 < L(E)C 50 ≤ 0,1 | 10 | 0,001 < NOEC ≤ 0,01 | 10 | 1', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-RD-B2', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, RD (rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, RD)', 'all', '>..<=', 0.001, 0.01, 'mg/l', null, 1, 'M factor', null, '0,01 < L(E)C 50 ≤ 0,1 | 10 | 0,001 < NOEC ≤ 0,01 | 10 | 1', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-NRD-B3', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, NRD (non-rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, NRD)', 'all', '>..<=', 0.0001, 0.001, 'mg/l', null, 100, 'M factor', null, '0,001 < L(E)C 50 ≤ 0,01 | 100 | 0,0001 < NOEC ≤ 0,001 | 100 | 10', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-RD-B3', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, RD (rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, RD)', 'all', '>..<=', 0.0001, 0.001, 'mg/l', null, 10, 'M factor', null, '0,001 < L(E)C 50 ≤ 0,01 | 100 | 0,0001 < NOEC ≤ 0,001 | 100 | 10', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-NRD-B4', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, NRD (non-rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, NRD)', 'all', '>..<=', 1e-05, 0.0001, 'mg/l', null, 1000, 'M factor', null, '0,0001 < L(E)C 50 ≤ 0,001 | 1 000 | 0,00001 < NOEC ≤ 0,0001 | 1 000 | 100', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-RD-B4', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, RD (rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, RD)', 'all', '>..<=', 1e-05, 0.0001, 'mg/l', null, 100, 'M factor', null, '0,0001 < L(E)C 50 ≤ 0,001 | 1 000 | 0,00001 < NOEC ≤ 0,0001 | 1 000 | 100', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-NRD-B5', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, NRD (non-rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, NRD)', 'all', '>..<=', 1e-06, 1e-05, 'mg/l', null, 10000, 'M factor', null, '0,00001 < L(E)C 50 ≤ 0,0001 | 10 000 | 0,000001 < NOEC ≤ 0,00001 | 10 000 | 1 000', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('T4.1.3-CHRONIC-RD-B5', 'M_FACTOR', 'AQUATIC_CHRONIC', '{AQUATIC_CHRONIC}', '4.1', 'Chronic 1 component, RD (rapidly degradable): NOEC value (mg/l)', 'M factor (chronic, RD)', 'all', '>..<=', 1e-06, 1e-05, 'mg/l', null, 1000, 'M factor', null, '0,00001 < L(E)C 50 ≤ 0,0001 | 10 000 | 0,000001 < NOEC ≤ 0,00001 | 10 000 | 1 000', 'Table 4.1.3', '4.1.3.5.5.5.1', 'M4', 'Multiplying factors for highly toxic components of mixtures. (1) Non-rapidly degradable. (2) Rapidly degradable. (continue in factor 10 intervals)', false),
('4.1.3.6.1-UNKNOWN', 'UNKNOWN_INGREDIENT', 'AQUATIC', '{AQUATIC_ACUTE,AQUATIC_CHRONIC}', '4.1', 'relevant component without useable aquatic hazard information', null, 'all', null, null, null, null, null, null, null, null, 'In the event that no useable information on short-term (acute) and/or long-term (chronic) aquatic hazard is available for one or more relevant components, it is concluded that the mixture cannot be attributed to one or more definitive hazard category(ies). In this situation the mixture shall be classified based on the known components only, with the additional statement on the label and in the SDS that: ‘Contains x % of components with unknown hazards to the aquatic environment’.', '4.1.3.6.1', '4.1.3.6', 'M2', 'порог — через «relevant components» 4.1.3.1 (0,1 % / 1 %)', false),
('T4.2.2-1', 'GCL', 'ED_ENV', '{}', '4.2', 'Category 1 endocrine disruptor for the environment', 'Category 1 endocrine disruptor for the environment', 'all', '>=', 0.1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 1 endocrine disruptor for the environment | ≥ 0,1 % |', 'Table 4.2.2', '4.2.3.1.1', 'M32', 'Note: The concentration limits in this Table apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 2 endocrine disruptor for the environment is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request. Application in time (4.2.3.4): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Sections 4.2.3.1 to 4.2.3.3. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Sections 4.2.3.1, 4.2.3.2 and 4.2.3.3 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('T4.2.2-2', 'GCL', 'ED_ENV', '{}', '4.2', 'Category 2 endocrine disruptor for the environment', 'Category 2 endocrine disruptor for the environment', 'all', '>=', 1, null, '% (w/w; v/v gases)', null, null, null, null, 'Category 2 endocrine disruptor for the environment | | ≥ 1 % [Note 1 ]', 'Table 4.2.2', '4.2.3.1.1', 'M32', 'Note: The concentration limits in this Table apply to solids and liquids (w/w units) as well as gases (v/v units). Note 1: If a Category 2 endocrine disruptor for the environment is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request. Application in time (4.2.3.4): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Sections 4.2.3.1 to 4.2.3.3. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Sections 4.2.3.1, 4.2.3.2 and 4.2.3.3 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('T4.2.2-2-SDS', 'SDS_TRIGGER', 'ED_ENV', '{}', '4.2', 'Category 2 endocrine disruptor for the environment', 'SDS available upon request', 'all', '>=', 0.1, null, '%', null, null, null, null, 'Note 1: If a Category 2 endocrine disruptor for the environment is present in the mixture as an ingredient at a concentration ≥ 0,1 % a SDS shall be available for the mixture upon request.', 'Table 4.2.2 Note 1', '4.2.3.1.1', 'M32', null, false),
('4.3.3.1-PBT', 'GCL', 'PBT_VPVB', '{}', '4.3', 'PBT', 'PBT', 'all', '>=', 0.1, null, '% w/w', null, null, null, null, 'A mixture shall be classified respectively as a PBT or vPvB when at least one component contained in the mixture has been classified respectively as a PBT or vPvB and is present at or above 0,1 % (weight/weight).', '4.3.3.1', '4.3.3', 'M32', 'Application in time (4.3.3.2): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Section 4.3.3.1. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Section 4.3.3.1 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('4.3.3.1-VPVB', 'GCL', 'PBT_VPVB', '{}', '4.3', 'vPvB', 'vPvB', 'all', '>=', 0.1, null, '% w/w', null, null, null, null, 'A mixture shall be classified respectively as a PBT or vPvB when at least one component contained in the mixture has been classified respectively as a PBT or vPvB and is present at or above 0,1 % (weight/weight).', '4.3.3.1', '4.3.3', 'M32', 'Application in time (4.3.3.2): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Section 4.3.3.1. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Section 4.3.3.1 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('4.4.3.1-PMT', 'GCL', 'PMT_VPVM', '{}', '4.4', 'PMT', 'PMT', 'all', '>=', 0.1, null, '% w/w', null, null, null, null, 'A mixture shall be classified as a PMT or vPvM where at least one of its components has been classified as a PMT or vPvM and is present at or above 0,1 % (weight/weight).', '4.4.3.1', '4.4.3', 'M32', 'Application in time (4.4.3.2): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Section 4.4.3.1. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Section 4.4.3.1 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('4.4.3.1-VPVM', 'GCL', 'PMT_VPVM', '{}', '4.4', 'vPvM', 'vPvM', 'all', '>=', 0.1, null, '% w/w', null, null, null, null, 'A mixture shall be classified as a PMT or vPvM where at least one of its components has been classified as a PMT or vPvM and is present at or above 0,1 % (weight/weight).', '4.4.3.1', '4.4.3', 'M32', 'Application in time (4.4.3.2): From 1 May 2026 at the latest, mixtures shall be classified in accordance with the criteria laid down in Section 4.4.3.1. However, mixtures which were placed on the market before 1 May 2026 are not required to be classified in accordance with the criteria laid down in Section 4.4.3.1 until 1 May 2028. ⚠ класса нет в hazard_class_catalog.', false),
('T5.1-OZONE', 'GCL', 'OZONE', '{OZONE}', '5.1', 'Hazardous to the ozone layer (Category 1)', 'Hazardous to the ozone layer (Category 1)', 'all', '>=', 0.1, null, '%', null, null, null, null, 'Hazardous to the ozone layer (Category 1) | C ≥ 0,1 %', 'Table 5.1', '5.1.3.1', 'M2', '⚠ hazard_class_catalog.ghs_chapter у OZONE = 4.2, в Annex I CLP это раздел 5.1 (в clp_category_criteria — 5.1).', false)
on conflict (rule_key) do update set kind=excluded.kind, class_code=excluded.class_code, catalog_codes=excluded.catalog_codes, ghs_chapter=excluded.ghs_chapter, ingredient_category=excluded.ingredient_category, result_category=excluded.result_category, physical_state=excluded.physical_state, operator=excluded.operator, limit_low=excluded.limit_low, limit_high=excluded.limit_high, unit=excluded.unit, weight_factor=excluded.weight_factor, value=excluded.value, value_unit=excluded.value_unit, formula_raw=excluded.formula_raw, raw=excluded.raw, source_ref=excluded.source_ref, source_section=excluded.source_section, marker=excluded.marker, note=excluded.note, needs_review=excluded.needs_review;
