-- ECHA Guidance on Labelling and Packaging v4.2 (March 2021), section 7.3.
-- Извлечено session 63 по координатам слов (pdftotext -bbox-layout), 93 страницы.
-- Класс и категория определены ЗАМЕРОМ: H-код + сигнальное слово из шапки
-- таблицы сопоставлены с clp_matrix_full. Неразобранных строк: 0.

-- 57 таблиц + 97 связок «таблица → класс + категория»

insert into echa_p_table (table_id, source_id, section, section_title, first_page, raw_categories) values
(1,'echa_lp_v4_2','7.3.2.1','Explosives',92,ARRAY['Unstable explosive Danger H200 Unstable explosive']::text[]),
(2,'echa_lp_v4_2','7.3.2.1','Explosives',94,ARRAY['Division 1.1 Danger H201 Explosive; mass explosion hazard','Division 1.2 Danger H202 Explosive; severe projection hazard','Division 1.3 Danger H203 Explosive; fire, blast or projection hazard']::text[]),
(3,'echa_lp_v4_2','7.3.2.1','Explosives',97,ARRAY['Division 1.4 Warning H204 Fire or projection hazard']::text[]),
(4,'echa_lp_v4_2','7.3.2.1','Explosives',99,ARRAY['pictogram','Division 1.5 Danger H205 May mass explode in fire']::text[]),
(5,'echa_lp_v4_2','7.3.2.2','Flammable gases (including chemically unstable gases)',102,ARRAY['Pictogram','1 Danger H220 Extremely flammable gas for hazard','category 1','2 Warning H221 Flammable gas','only.']::text[]),
(6,'echa_lp_v4_2','7.3.2.2','Flammable gases (including chemically unstable gases)',103,ARRAY['pictogram','A No additional signal word H230 May react explosively even in the absence of air','B No additional signal word H231 May react explosively even in the absence of air','at elevated pressure and/or temperature']::text[]),
(7,'echa_lp_v4_2','7.3.2.3','Aerosols',104,ARRAY['1 Danger H222 Extremely flammable aerosol','H229 Pressurised container: May burst if heated','2 Warning H223 Flammable aerosol','H229 Pressurised container: May burst if heated']::text[]),
(8,'echa_lp_v4_2','7.3.2.3','Aerosols (continued) hazard',105,ARRAY['3 Warning H229 Pressurised container: May burst if heated']::text[]),
(9,'echa_lp_v4_2','7.3.2.4','Oxidising gases',106,ARRAY['1 Danger H270 May cause or intensify fire; oxidiser']::text[]),
(10,'echa_lp_v4_2','7.3.2.5','Gases under pressure',107,ARRAY['Compressed gas Warning H280 Contains gas under pressure; may explode if heated','Liquefied gas Warning H280 Contains gas under pressure; may explode if heated','Dissolved gas Warning H280 Contains gas under pressure; may explode if heated']::text[]),
(11,'echa_lp_v4_2','7.3.2.5','Gases under pressure',108,ARRAY['Refrigerated liquefied gas Warning H281 Contains refrigerated gas; may cause cryogenic burns or injury']::text[]),
(12,'echa_lp_v4_2','7.3.2.6','Flammable liquids',109,ARRAY['1 Danger H224 Extremely flammable liquid and vapour','2 Danger H225 Highly flammable liquid and vapour','3 Warning H226 Flammable liquid and vapour']::text[]),
(13,'echa_lp_v4_2','7.3.2.7','Flammable solids',112,ARRAY['1 Danger H228 Flammable solid','2 Warning H228 Flammable solid']::text[]),
(14,'echa_lp_v4_2','7.3.2.8','Self-reactive substances and mixtures',114,ARRAY['Type A Danger H240 Heating may cause an explosion']::text[]),
(15,'echa_lp_v4_2','7.3.2.8','Self-reactive substances and mixtures',116,ARRAY['Type B Danger H241 Heating may cause a fire or explosion']::text[]),
(16,'echa_lp_v4_2','7.3.2.8','Self-reactive substances and mixtures',118,ARRAY['Type C Danger H242 Heating may cause a fire','Type D Danger H242 Heating may cause a fire','Type E Warning H242 Heating may cause a fire','Type F Warning H242 Heating may cause a fire']::text[]),
(17,'echa_lp_v4_2','7.3.2.9','Pyrophoric liquids',120,ARRAY['1 Danger H250 Catches fire spontaneously if exposed to air']::text[]),
(18,'echa_lp_v4_2','7.3.2.10','Pyrophoric solids',122,ARRAY['1 Danger H250 Catches fire spontaneously if exposed to air']::text[]),
(19,'echa_lp_v4_2','7.3.2.11','Self-heating substances and mixtures',124,ARRAY['1 Danger H251 Self-heating; may catch fire','2 Warning H252 Self-heating in large quantities; may catch fire']::text[]),
(20,'echa_lp_v4_2','7.3.2.12','Substances and mixtures which, in contact with water, emit flammable gases',125,ARRAY['1 Danger H260 In contact with water releases flammable gases which may','ignite spontaneously','2 Danger H261 In contact with water releases flammable gases']::text[]),
(21,'echa_lp_v4_2','7.3.2.12','Substances and mixtures which, in contact with water, emit flammable gases',127,ARRAY['3 Warning H261 In contact with water releases flammable gases']::text[]),
(22,'echa_lp_v4_2','7.3.2.13','Oxidising liquids',128,ARRAY['1 Danger H271 May cause fire or explosion; strong oxidizer']::text[]),
(23,'echa_lp_v4_2','7.3.2.13','Oxidising liquids',130,ARRAY['2 Danger H272 May intensify fire; oxidiser','3 Warning H272 May intensify fire; oxidiser']::text[]),
(24,'echa_lp_v4_2','7.3.2.14','Oxidising solids',131,ARRAY['1 Danger H271 May cause fire or explosion; strong oxidizer']::text[]),
(25,'echa_lp_v4_2','7.3.2.14','Oxidising solids',132,ARRAY['2 Danger H272 May intensify fire; oxidiser','3 Warning H272 May intensify fire; oxidiser']::text[]),
(26,'echa_lp_v4_2','7.3.2.15','Organic peroxides',133,ARRAY['Type A Danger H240 Heating may cause an explosion']::text[]),
(27,'echa_lp_v4_2','7.3.2.15','Organic peroxides',135,ARRAY['Type B Danger H241 Heating may cause a fire or explosion']::text[]),
(28,'echa_lp_v4_2','7.3.2.15','Organic peroxides',137,ARRAY['Type C Danger H242 Heating may cause a fire','Type D Danger H242 Heating may cause a fire','Type E Warning H242 Heating may cause a fire','Type F Warning H242 Heating may cause a fire']::text[]),
(29,'echa_lp_v4_2','7.3.2.16','Corrosive to metals',139,ARRAY['1 Warning H290 May be corrosive to metals']::text[]),
(30,'echa_lp_v4_2','7.3.3.1','Acute Toxicity – Oral',140,ARRAY['1 Danger H300 Fatal if swallowed','2 Danger H300 Fatal if swallowed','3 Danger H301 Toxic if swallowed']::text[]),
(31,'echa_lp_v4_2','7.3.3.1','Acute Toxicity – Oral',142,ARRAY['4 Warning H302 Harmful if swallowed']::text[]),
(32,'echa_lp_v4_2','7.3.3.1','Acute Toxicity – Dermal',143,ARRAY['1 Danger H310 Fatal in contact with skin','2 Danger H310 Fatal in contact with skin']::text[]),
(33,'echa_lp_v4_2','7.3.3.1','Acute Toxicity – Dermal',145,ARRAY['3 Danger H311 Toxic in contact with skin']::text[]),
(34,'echa_lp_v4_2','7.3.3.1','Acute Toxicity – Dermal',147,ARRAY['4 Warning H312 Harmful in contact with skin']::text[]),
(35,'echa_lp_v4_2','7.3.3.1','Acute Toxicity - Inhalation',149,ARRAY['1 Danger H330 Fatal if inhaled','2 Danger H330 Fatal if inhaled']::text[]),
(36,'echa_lp_v4_2','7.3.3.1','Acute Toxicity – Inhalation',151,ARRAY['3 Danger H331 Toxic if inhaled']::text[]),
(37,'echa_lp_v4_2','7.3.3.1','Acute Toxicity – Inhalation',152,ARRAY['4 Warning H332 Harmful if inhaled']::text[]),
(38,'echa_lp_v4_2','7.3.3.2','Skin corrosion/irritation',153,ARRAY['Sub-categories 1A, 1B, 1C','and Category 1 Danger H314 Causes severe skin burns and eye damage']::text[]),
(39,'echa_lp_v4_2','7.3.3.2','Skin corrosion/irritation',156,ARRAY['2 Warning H315 Causes skin irritation']::text[]),
(40,'echa_lp_v4_2','7.3.3.3','Serious eye damage - only 52',158,ARRAY['1 Danger H318 Causes serious eye damage']::text[]),
(41,'echa_lp_v4_2','7.3.3.3','Eye irritation – only 53',159,ARRAY['2 Warning H319 Causes serious eye irritation']::text[]),
(42,'echa_lp_v4_2','7.3.3.4','Respiratory sensitisation',160,ARRAY['1, 1A, 1B Danger H334 May cause allergy or asthma symptoms or breathing','difficulties if inhaled']::text[]),
(43,'echa_lp_v4_2','7.3.3.4','Skin sensitisation',161,ARRAY['1, 1A, 1B Warning H317 May cause an allergic skin reaction']::text[]),
(44,'echa_lp_v4_2','7.3.3.5','Germ cell mutagenicity',163,ARRAY['1A and 1B Danger H340 May cause genetic defects (state route of exposure if it is','conclusively proven that no other routes of exposure cause','the hazard)','2 Warning H341 Suspected of causing genetic defects (state route of exposure','if it is conclusively proven that no other routes of exposure cause','the hazard)']::text[]),
(45,'echa_lp_v4_2','7.3.3.6','Carcinogenicity',165,ARRAY['1A and 1B Danger H350 May cause cancer (state route of exposure if it is conclusively','proven that no other routes of exposure cause the hazard)','2 Warning H351 Suspected of causing cancer (state route of exposure if it is','conclusively proven that no other routes of exposure cause the','hazard)']::text[]),
(46,'echa_lp_v4_2','7.3.3.7','Reproductive toxicity',167,ARRAY['1A and 1B Danger H360 May damage fertility or the unborn child','(state specific effect if known)','(state route of exposure if it is conclusively proven','that no other routes of exposure cause the hazard)','2 Warning H361 Suspected of damaging fertility or the unborn child','(state specific effect if known)','(state route of exposure if it is conclusively proven that','no other routes of exposure cause the hazard)']::text[]),
(47,'echa_lp_v4_2','7.3.3.7','Reproductive toxicity',169,ARRAY['Additional category for effects on','or via lactation No signal word H362 May cause harm to breast-fed children']::text[]),
(48,'echa_lp_v4_2','7.3.3.8','Specific target organ toxicity after single exposure',171,ARRAY['1 Danger H370 Causes damage to organs (or state all organs affected, if known)','(state route of exposure if it is conclusively proven that no other','routes of exposure cause the hazard)']::text[]),
(49,'echa_lp_v4_2','7.3.3.8','Specific target organ toxicity after single exposure',173,ARRAY['2 Warning H371 May cause damage to organs (or state all organs affected, if','known)','(state route of exposure if it is conclusively proven that no other','routes of exposure cause the hazard)']::text[]),
(50,'echa_lp_v4_2','7.3.3.8','Specific target organ toxicity after single exposure',175,ARRAY['3 Warning H335 May cause respiratory irritation; or','H336 May cause drowsiness or dizziness']::text[]),
(51,'echa_lp_v4_2','7.3.3.9','Specific target organ toxicity after repeated exposure',176,ARRAY['1 Danger H372 Causes damage to organs (state all organs affected, if known)','through prolonged or repeated exposure (state route of','exposure if it is conclusively proven that no other routes of','exposure cause the hazard)']::text[]),
(52,'echa_lp_v4_2','7.3.3.9','Specific target organ toxicity after repeated exposure',178,ARRAY['2 Warning H373 May cause damage to organs (state all organs affected, if','known) through prolonged or repeated exposure (state route of','exposure if it is conclusively proven that no other routes of','exposure','cause the hazard)']::text[]),
(53,'echa_lp_v4_2','7.3.3.10','Aspiration hazard',179,ARRAY['1 Danger H304 May be fatal if swallowed and enters airways']::text[]),
(54,'echa_lp_v4_2','7.3.4.1','Hazardous to the aquatic environment – short-term (acute) aquatic hazard',180,ARRAY['1 Warning H400 Very toxic to aquatic life']::text[]),
(55,'echa_lp_v4_2','7.3.4.1','Hazardous to the aquatic environment – long-term (chronic) aquatic hazard',181,ARRAY['1 Warning H410 Very toxic to aquatic life with long lasting effects','2 No signal word H411 Toxic to aquatic life with long lasting effects']::text[]),
(56,'echa_lp_v4_2','7.3.4.1','Hazardous to the aquatic environment – long-term (chronic) aquatic hazard',182,ARRAY['pictogram','is used 3 No signal word H412 Harmful to aquatic life with long lasting effects','4 No signal word H413 May cause long lasting harmful effects to aquatic life']::text[]),
(57,'echa_lp_v4_2','7.3.5.1','Hazardous to the ozone layer',183,ARRAY['1 Warning H420 Harms public health and the environment by destroying ozone','in the upper atmosphere']::text[]) on conflict do nothing;
insert into echa_p_table_scope (table_id, class_code, category_code, mapped_by, note) values
(1,'EXPLOSIVES','Unstable explosive','h_code+signal_word','Unstable explosive Danger H200 Unstable explosive'),
(2,'EXPLOSIVES','Division 1.1','h_code+signal_word','Division 1.1 Danger H201 Explosive; mass explosion hazard'),
(2,'EXPLOSIVES','Division 1.2','h_code+signal_word','Division 1.2 Danger H202 Explosive; severe projection hazard'),
(2,'EXPLOSIVES','Division 1.3','h_code+signal_word','Division 1.3 Danger H203 Explosive; fire, blast or projection hazard'),
(3,'EXPLOSIVES','Division 1.4','h_code+signal_word','Division 1.4 Warning H204 Fire or projection hazard'),
(4,'EXPLOSIVES','Division 1.5','h_code+signal_word','Division 1.5 Danger H205 May mass explode in fire'),
(5,'FLAM_GAS','1A','h_code+signal_word','1 Danger H220 Extremely flammable gas for hazard'),
(5,'FLAM_GAS','2','h_code+signal_word','2 Warning H221 Flammable gas'),
(6,'FLAM_GAS','A','h_code+signal_word','A No additional signal word H230 May react explosively even in the absence of air'),
(6,'FLAM_GAS','B','h_code+signal_word','B No additional signal word H231 May react explosively even in the absence of air'),
(7,'AEROSOL','1','h_code+signal_word','1 Danger H222 Extremely flammable aerosol'),
(7,'AEROSOL','3','h_code+signal_word','H229 Pressurised container: May burst if heated'),
(7,'AEROSOL','2','h_code+signal_word','2 Warning H223 Flammable aerosol'),
(8,'AEROSOL','3','h_code+signal_word','3 Warning H229 Pressurised container: May burst if heated'),
(9,'OX_GAS','1','h_code+signal_word','1 Danger H270 May cause or intensify fire; oxidiser'),
(10,'GAS_PRESSURE','Compressed gas','h_code+signal_word(multi)','Compressed gas Warning H280 Contains gas under pressure; may explode if heated'),
(10,'GAS_PRESSURE','Dissolved gas','h_code+signal_word(multi)','Compressed gas Warning H280 Contains gas under pressure; may explode if heated'),
(10,'GAS_PRESSURE','Liquefied gas','h_code+signal_word(multi)','Compressed gas Warning H280 Contains gas under pressure; may explode if heated'),
(11,'GAS_PRESSURE','Refrigerated liquefied gas','h_code+signal_word','Refrigerated liquefied gas Warning H281 Contains refrigerated gas; may cause cryogenic burns or injury'),
(12,'FLAM_LIQ','1','h_code+signal_word','1 Danger H224 Extremely flammable liquid and vapour'),
(12,'FLAM_LIQ','2','h_code+signal_word','2 Danger H225 Highly flammable liquid and vapour'),
(12,'FLAM_LIQ','3','h_code+signal_word','3 Warning H226 Flammable liquid and vapour'),
(13,'FLAM_SOL','1','h_code+signal_word','1 Danger H228 Flammable solid'),
(13,'FLAM_SOL','2','h_code+signal_word','2 Warning H228 Flammable solid'),
(14,'SELF_REACTIVE','Type A','h_code+signal_word','Type A Danger H240 Heating may cause an explosion'),
(15,'SELF_REACTIVE','Type B','h_code+signal_word','Type B Danger H241 Heating may cause a fire or explosion'),
(16,'SELF_REACTIVE','Type C','h_code+signal_word(multi)','Type C Danger H242 Heating may cause a fire'),
(16,'SELF_REACTIVE','Type D','h_code+signal_word(multi)','Type C Danger H242 Heating may cause a fire'),
(16,'SELF_REACTIVE','Type E','h_code+signal_word(multi)','Type E Warning H242 Heating may cause a fire'),
(16,'SELF_REACTIVE','Type F','h_code+signal_word(multi)','Type E Warning H242 Heating may cause a fire'),
(17,'PYRO_LIQ','1','h_code+signal_word','1 Danger H250 Catches fire spontaneously if exposed to air'),
(18,'PYRO_SOL','1','h_code+signal_word','1 Danger H250 Catches fire spontaneously if exposed to air'),
(19,'SELF_HEATING','1','h_code+signal_word','1 Danger H251 Self-heating; may catch fire'),
(19,'SELF_HEATING','2','h_code+signal_word','2 Warning H252 Self-heating in large quantities; may catch fire'),
(20,'WATER_REACTIVE','1','h_code+signal_word','1 Danger H260 In contact with water releases flammable gases which may'),
(20,'WATER_REACTIVE','2','h_code+signal_word','2 Danger H261 In contact with water releases flammable gases'),
(21,'WATER_REACTIVE','3','h_code+signal_word','3 Warning H261 In contact with water releases flammable gases'),
(22,'OX_LIQ','1','h_code+signal_word','1 Danger H271 May cause fire or explosion; strong oxidizer'),
(23,'OX_LIQ','2','h_code+signal_word','2 Danger H272 May intensify fire; oxidiser'),
(23,'OX_LIQ','3','h_code+signal_word','3 Warning H272 May intensify fire; oxidiser'),
(24,'OX_SOL','1','h_code+signal_word','1 Danger H271 May cause fire or explosion; strong oxidizer'),
(25,'OX_SOL','2','h_code+signal_word','2 Danger H272 May intensify fire; oxidiser'),
(25,'OX_SOL','3','h_code+signal_word','3 Warning H272 May intensify fire; oxidiser'),
(26,'ORG_PEROXIDE','Type A','h_code+signal_word','Type A Danger H240 Heating may cause an explosion'),
(27,'ORG_PEROXIDE','Type B','h_code+signal_word','Type B Danger H241 Heating may cause a fire or explosion'),
(28,'ORG_PEROXIDE','Type C','h_code+signal_word(multi)','Type C Danger H242 Heating may cause a fire'),
(28,'ORG_PEROXIDE','Type D','h_code+signal_word(multi)','Type C Danger H242 Heating may cause a fire'),
(28,'ORG_PEROXIDE','Type E','h_code+signal_word(multi)','Type E Warning H242 Heating may cause a fire'),
(28,'ORG_PEROXIDE','Type F','h_code+signal_word(multi)','Type E Warning H242 Heating may cause a fire'),
(29,'CORR_METAL','1','h_code+signal_word','1 Warning H290 May be corrosive to metals'),
(30,'ACUTE_TOX_ORAL','1','h_code+signal_word(multi)','1 Danger H300 Fatal if swallowed'),
(30,'ACUTE_TOX_ORAL','2','h_code+signal_word(multi)','1 Danger H300 Fatal if swallowed'),
(30,'ACUTE_TOX_ORAL','3','h_code+signal_word','3 Danger H301 Toxic if swallowed'),
(31,'ACUTE_TOX_ORAL','4','h_code+signal_word','4 Warning H302 Harmful if swallowed'),
(32,'ACUTE_TOX_DERMAL','1','h_code+signal_word(multi)','1 Danger H310 Fatal in contact with skin'),
(32,'ACUTE_TOX_DERMAL','2','h_code+signal_word(multi)','1 Danger H310 Fatal in contact with skin'),
(33,'ACUTE_TOX_DERMAL','3','h_code+signal_word','3 Danger H311 Toxic in contact with skin'),
(34,'ACUTE_TOX_DERMAL','4','h_code+signal_word','4 Warning H312 Harmful in contact with skin'),
(35,'ACUTE_TOX_INHAL','1','h_code+signal_word(multi)','1 Danger H330 Fatal if inhaled'),
(35,'ACUTE_TOX_INHAL','2','h_code+signal_word(multi)','1 Danger H330 Fatal if inhaled'),
(36,'ACUTE_TOX_INHAL','3','h_code+signal_word','3 Danger H331 Toxic if inhaled'),
(37,'ACUTE_TOX_INHAL','4','h_code+signal_word','4 Warning H332 Harmful if inhaled'),
(38,'SKIN_CORR_IRRIT','1A','h_code+signal_word(multi)','and Category 1 Danger H314 Causes severe skin burns and eye damage'),
(38,'SKIN_CORR_IRRIT','1B','h_code+signal_word(multi)','and Category 1 Danger H314 Causes severe skin burns and eye damage'),
(38,'SKIN_CORR_IRRIT','1C','h_code+signal_word(multi)','and Category 1 Danger H314 Causes severe skin burns and eye damage'),
(39,'SKIN_CORR_IRRIT','2','h_code+signal_word','2 Warning H315 Causes skin irritation'),
(40,'EYE_DAMAGE_IRRIT','1','h_code+signal_word','1 Danger H318 Causes serious eye damage'),
(41,'EYE_DAMAGE_IRRIT','2','h_code+signal_word','2 Warning H319 Causes serious eye irritation'),
(42,'RESP_SENS','1','h_code+signal_word(multi)','1, 1A, 1B Danger H334 May cause allergy or asthma symptoms or breathing'),
(42,'RESP_SENS','1A','h_code+signal_word(multi)','1, 1A, 1B Danger H334 May cause allergy or asthma symptoms or breathing'),
(42,'RESP_SENS','1B','h_code+signal_word(multi)','1, 1A, 1B Danger H334 May cause allergy or asthma symptoms or breathing'),
(43,'SKIN_SENS','1','h_code+signal_word(multi)','1, 1A, 1B Warning H317 May cause an allergic skin reaction'),
(43,'SKIN_SENS','1A','h_code+signal_word(multi)','1, 1A, 1B Warning H317 May cause an allergic skin reaction'),
(43,'SKIN_SENS','1B','h_code+signal_word(multi)','1, 1A, 1B Warning H317 May cause an allergic skin reaction'),
(44,'MUTAGEN','1A','h_code+signal_word(multi)','1A and 1B Danger H340 May cause genetic defects (state route of exposure if it is'),
(44,'MUTAGEN','1B','h_code+signal_word(multi)','1A and 1B Danger H340 May cause genetic defects (state route of exposure if it is'),
(44,'MUTAGEN','2','h_code+signal_word','2 Warning H341 Suspected of causing genetic defects (state route of exposure'),
(45,'CARCINOGEN','1A','h_code+signal_word(multi)','1A and 1B Danger H350 May cause cancer (state route of exposure if it is conclusively'),
(45,'CARCINOGEN','1B','h_code+signal_word(multi)','1A and 1B Danger H350 May cause cancer (state route of exposure if it is conclusively'),
(45,'CARCINOGEN','2','h_code+signal_word','2 Warning H351 Suspected of causing cancer (state route of exposure if it is'),
(46,'REPRO_TOX','1A','h_code+signal_word(multi)','1A and 1B Danger H360 May damage fertility or the unborn child'),
(46,'REPRO_TOX','1B','h_code+signal_word(multi)','1A and 1B Danger H360 May damage fertility or the unborn child'),
(46,'REPRO_TOX','2','h_code+signal_word','2 Warning H361 Suspected of damaging fertility or the unborn child'),
(47,'REPRO_TOX','Additional category','h_code+signal_word','or via lactation No signal word H362 May cause harm to breast-fed children'),
(48,'STOT_SE','1','h_code+signal_word','1 Danger H370 Causes damage to organs (or state all organs affected, if known)'),
(49,'STOT_SE','2','h_code+signal_word','2 Warning H371 May cause damage to organs (or state all organs affected, if'),
(50,'STOT_SE','3','h_code+signal_word','3 Warning H335 May cause respiratory irritation; or'),
(50,'STOT_SE','3 narcotic','h_code+signal_word','H336 May cause drowsiness or dizziness'),
(51,'STOT_RE','1','h_code+signal_word','1 Danger H372 Causes damage to organs (state all organs affected, if known)'),
(52,'STOT_RE','2','h_code+signal_word','2 Warning H373 May cause damage to organs (state all organs affected, if'),
(53,'ASPIRATION','1','h_code+signal_word','1 Danger H304 May be fatal if swallowed and enters airways'),
(54,'AQUATIC_ACUTE','1','h_code+signal_word','1 Warning H400 Very toxic to aquatic life'),
(55,'AQUATIC_CHRONIC','1','h_code+signal_word','1 Warning H410 Very toxic to aquatic life with long lasting effects'),
(55,'AQUATIC_CHRONIC','2','h_code+signal_word','2 No signal word H411 Toxic to aquatic life with long lasting effects'),
(56,'AQUATIC_CHRONIC','3','h_code+signal_word','is used 3 No signal word H412 Harmful to aquatic life with long lasting effects'),
(56,'AQUATIC_CHRONIC','4','h_code+signal_word','4 No signal word H413 May cause long lasting harmful effects to aquatic life'),
(57,'OZONE','1','h_code+signal_word','1 Warning H420 Harms public health and the environment by destroying ozone') on conflict do nothing;
