-- ECHA Guidance on Labelling and Packaging v4.2 (March 2021), section 7.3.
-- Извлечено session 63 по координатам слов (pdftotext -bbox-layout), 93 страницы.
-- Класс и категория определены ЗАМЕРОМ: H-код + сигнальное слово из шапки
-- таблицы сопоставлены с clp_matrix_full. Неразобранных строк: 0.

-- 444 атомарных рекомендации

insert into echa_p_recommendation (block_id, seq, level, scope, audience, condition_text) values
(1,1,'highly_recommended','label','both','Highly recommended '),
(2,1,'highly_recommended','label','both','Highly recommended if the  explosive is mechanically sensitive'),
(2,2,'optional','label','both','Optional if the explosive is not  mechanically sensitive'),
(3,1,'highly_recommended','label','both','Highly recommended '),
(4,1,'highly_recommended','sds','both','Highly recommended for  inclusion in the safety data sheet. Specify the applicable regulation.'),
(5,1,'recommended','sds','both','Recommended for  inclusion in the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals.'),
(6,1,'highly_recommended','label','both','Highly recommended to apply the  full wording of P280'),
(7,1,'highly_recommended','label','both','Highly recommended '),
(8,1,'highly_recommended','label','both','Highly recommended '),
(9,1,'highly_recommended','label','both','Highly recommended '),
(10,1,'highly_recommended','label','both','Highly recommended '),
(11,1,'highly_recommended','sds','both','Highly recommended for  inclusion in the safety data sheet. Specify the applicable regulation.'),
(12,1,'recommended','label','general_public','Recommended for inclusion  in the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation. Mandatory when supplied  to the general public (where the Member State allows such supply).'),
(13,1,'optional','label','both','Optional unless other conditions  deem it necessary'),
(13,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(14,1,'highly_recommended','label','both','Highly recommended if the  explosive is mechanically sensitive'),
(14,2,'optional','label','both','Optional if the explosive is not  mechanically sensitive'),
(15,1,'highly_recommended','label','professional','highly recommended for industrial/professional users Face protection highly '),
(15,2,'recommended','label','professional','recommended for industrial/professional users where articles are able to form hazardous fragments'),
(15,3,'recommended','label','general_public','Recommended for explosives  supplied to the general public (where Member States allows such supply).'),
(16,1,'highly_recommended','label','both','Highly recommended '),
(17,1,'highly_recommended','label','both','Highly recommended '),
(18,1,'optional','label','both','Optional unless other conditions deem it  necessary'),
(18,2,'recommended','label','both','Recommended for inclusion in the safety  data sheet'),
(19,1,'highly_recommended','label','both','Highly recommended '),
(20,1,'highly_recommended','label','both','Highly recommended '),
(21,1,'highly_recommended','sds','both','Highly recommended for  inclusion in the safety data sheet. Specify the applicable regulation.'),
(22,1,'recommended','sds','general_public','Recommended for  inclusion in the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation. Mandatory when supplied  to the general public'),
(23,1,'highly_recommended','label','both','Highly recommended if the explosive is  mechanically sensitive'),
(23,2,'optional','label','both','Optional if the explosive is not  mechanically sensitive'),
(24,1,'highly_recommended','label','professional','highly recommended for industrial / professional users Face protection'),
(24,2,'highly_recommended','label','professional','highly recommended for  industrial / professional users where articles are able to form hazardous fragments'),
(24,3,'recommended','label','general_public','Recommended for explosives supplied to  the general public (where Member States allows such supply).'),
(25,1,'highly_recommended','label','both','Highly recommended '),
(26,1,'highly_recommended','label','both','Highly recommended '),
(27,1,'highly_recommended','label','both','Highly recommended '),
(28,1,'highly_recommended','label','both','Highly recommended '),
(29,1,'highly_recommended','sds','both','Highly recommended for  inclusion in the safety data sheet. Specify the applicable regulation.'),
(30,1,'recommended','sds','general_public','Recommended for  inclusion in the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation. Mandatory when  supplied to the general public (where the Member State allows such supply).'),
(31,1,'optional','label','both','Optional unless other conditions  deem it necessary'),
(31,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(32,1,'highly_recommended','label','both','Highly recommended if the explosive  is mechanically sensitive'),
(32,2,'optional','label','both','Optional if the explosive is not  mechanically sensitive'),
(34,1,'highly_recommended','label','both','Highly recommended '),
(35,1,'highly_recommended','label','both','Highly recommended '),
(36,1,'recommended','label','both','Recommended '),
(37,1,'highly_recommended','label','both','Highly recommended '),
(38,1,'highly_recommended','label','both','Highly recommended  Note: This table lists only the precautionary statements that are assigned based previous page.'),
(46,1,'highly_recommended','label','both','Highly recommended '),
(47,1,'highly_recommended','label','both','Highly recommended '),
(48,1,'optional','label','both','Optional '),
(48,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet.'),
(49,1,'highly_recommended','label','both','Highly recommended '),
(50,1,'optional','label','both','Optional '),
(51,1,'highly_recommended','label','both','Highly recommended where liquid  splashes may occur, e.g. during transfer of cryogenic liquids. In this case the use of safety glasses with side shields or a face shield should be indicated in the safety data sheet.'),
(52,1,'recommended','label','both','Recommended '),
(53,1,'optional','label','both','Optional '),
(54,1,'highly_recommended','label','both','Highly recommended '),
(55,1,'highly_recommended','label','both','Highly recommended for category 1, unless  P404 has already been assigned'),
(55,2,'recommended','label','both','Recommended for category 2, unless P404  has already been assigned'),
(55,3,'optional','label','both','Optional for category 3 '),
(57,1,'highly_recommended','label','both','Highly recommended, unless P403 + P235 is  assigned.'),
(58,1,'optional','label','both','Optional unless other conditions deem it  necessary'),
(58,2,'recommended','label','both','Recommended for inclusion in the safety  data sheet'),
(59,1,'optional','label','both','Optional unless other conditions deem it  necessary'),
(60,1,'optional','label','both','Optional unless other conditions deem it  necessary'),
(60,2,'recommended','label','both','Recommended for inclusion in the safety  data sheet'),
(61,1,'optional','label','both','Optional unless other conditions deem it  necessary'),
(61,2,'recommended','label','both','Recommended for inclusion in the safety  data sheet'),
(62,1,'optional','label','both','Optional '),
(63,1,'highly_recommended','label','both','Highly recommended '),
(64,1,'optional','label','both','Optional unless other conditions deem it  necessary'),
(64,2,'recommended','label','both','Recommended for inclusion in the safety data  sheet'),
(65,1,'highly_recommended','label','both','Highly recommended if specific  extinguishing media are required or appropriate'),
(66,1,'optional','label','both','Optional unless other conditions deem it  necessary'),
(66,2,'recommended','label','both','Recommended for inclusion in the safety data  sheet'),
(67,1,'optional','label','both','Optional '),
(68,1,'highly_recommended','label','both','Highly recommended '),
(69,1,'highly_recommended','label','both','Highly recommended where the  packaging is important for preventing or suppressing the effect of dangerous reactions or explosion'),
(70,1,'recommended','label','both','Recommended '),
(71,1,'highly_recommended','label','both','Highly recommended '),
(72,1,'highly_recommended','label','both','Highly recommended '),
(74,1,'recommended','label','both','Recommended for inclusion  in the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(75,1,'optional','label','both','Optional unless other conditions deem  it necessary'),
(75,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(76,1,'highly_recommended','label','both','Highly recommended '),
(77,1,'recommended','label','both','Recommended where  incompatible materials are likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information.'),
(78,1,'highly_recommended','label','both','Highly recommended '),
(79,1,'highly_recommended','label','both','Highly recommended '),
(80,1,'recommended','label','both','Recommended '),
(82,1,'highly_recommended','label','both','Highly recommended '),
(84,1,'recommended','label','both','recommended to specify the site of disposal while a'),
(85,1,'highly_recommended','label','both','Highly recommended '),
(86,1,'recommended','label','both','Recommended where  incompatible materials are likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information'),
(87,1,'highly_recommended','label','both','Highly recommended '),
(88,1,'highly_recommended','label','both','Highly recommended '),
(89,1,'recommended','label','both','Recommended '),
(90,1,'highly_recommended','label','both','Highly recommended if specific  extinguishing media are required or appropriate'),
(91,1,'highly_recommended','label','both','Highly recommended '),
(93,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(93,2,'recommended','label','both','Recommended for inclusion in  the safety data sheet if there'),
(94,1,'optional','label','both','Optional unless other conditions deem  it necessary'),
(94,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(95,1,'highly_recommended','label','both','Highly recommended '),
(96,1,'recommended','label','both','Recommended where  incompatible materials are likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information'),
(97,1,'highly_recommended','label','both','Highly recommended '),
(98,1,'optional','label','both','Optional '),
(99,1,'recommended','label','both','Recommended '),
(99,2,'highly_recommended','label','both','Highly recommended for inclusion in the  safety data sheet'),
(100,1,'highly_recommended','label','both','Highly recommended '),
(101,1,'highly_recommended','label','both','Highly recommended if specific extinguishing  media are required or appropriate'),
(102,1,'highly_recommended','label','both','Highly recommended '),
(103,1,'highly_recommended','label','both','Highly recommended '),
(104,1,'highly_recommended','label','both','Highly recommended '),
(105,1,'optional','label','both','Optional '),
(106,1,'recommended','label','both','Recommended '),
(107,1,'highly_recommended','label','both','Highly recommended '),
(108,1,'highly_recommended','label','both','Highly recommended if specific  extinguishing media are required or appropriate'),
(109,1,'highly_recommended','label','both','Highly recommended '),
(110,1,'highly_recommended','label','both','Highly recommended '),
(111,1,'highly_recommended','label','both','Highly recommended for the general  public'),
(112,1,'optional','label','both','Optional '),
(113,1,'highly_recommended','label','both','Highly recommended '),
(114,1,'highly_recommended','label','both','Highly recommended if the manufacturer has  specific information'),
(115,1,'recommended','label','both','Recommended where incompatible materials are  likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information'),
(116,1,'optional','label','both','Optional '),
(117,1,'highly_recommended','label','both','Highly recommended where special emphasis is  required'),
(118,1,'highly_recommended','label','both','Highly recommended '),
(119,1,'highly_recommended','label','both','Highly recommended if  specific extinguishing media are required or appropriate'),
(120,1,'recommended','label','both','Recommended, unless  P231 has already been assigned'),
(120,2,'highly_recommended','sds','both','Highly recommended for  inclusion in the safety data sheet'),
(121,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(122,1,'recommended','label','both','Recommended '),
(123,1,'highly_recommended','label','both','Highly recommended where special  emphasis is required'),
(124,1,'recommended','label','both','Recommended '),
(125,1,'highly_recommended','label','both','Highly recommended if specific  extinguishing media are required or appropriate'),
(126,1,'recommended','label','both','Recommended, unless P231  has already been assigned'),
(126,2,'highly_recommended','sds','both','Highly recommended for  inclusion in the safety data sheet'),
(127,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(127,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(128,1,'highly_recommended','label','both','Highly recommended '),
(129,1,'highly_recommended','label','both','Highly recommended '),
(130,1,'recommended','label','both','Recommended '),
(131,1,'recommended','label','both','Recommended '),
(132,1,'highly_recommended','label','both','Highly recommended '),
(134,1,'recommended','label','both','Recommended where  incompatible materials are likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information'),
(134,2,'optional','label','both','Optional where P220 has  already been assigned'),
(135,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(135,2,'recommended','label','both','Recommended for inclusion in  the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals'),
(136,1,'recommended','label','both','Recommended for inclusion in  the safety data sheet'),
(137,1,'highly_recommended','label','both','Highly recommended '),
(138,1,'highly_recommended','label','both','Highly recommended '),
(139,1,'recommended','label','both','Recommended '),
(140,1,'highly_recommended','label','both','Highly recommended if  specific extinguishing media are required or appropriate'),
(141,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(141,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(142,1,'highly_recommended','label','both','Highly recommended '),
(143,1,'highly_recommended','label','both','Highly recommended '),
(144,1,'recommended','label','both','Recommended '),
(145,1,'recommended','label','both','Recommended for inclusion in the safety data  sheet') on conflict do nothing;

insert into echa_p_recommendation (block_id, seq, level, scope, audience, condition_text) values
(146,1,'recommended','label','both','Recommended '),
(147,1,'highly_recommended','label','both','Highly recommended '),
(148,1,'highly_recommended','label','both','Highly recommended if specific  extinguishing media are required or appropriate'),
(149,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(149,2,'recommended','label','both','Recommended for inclusion in  the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(150,1,'highly_recommended','label','both','Highly recommended '),
(151,1,'highly_recommended','label','both','Highly recommended '),
(152,1,'recommended','label','both','Recommended '),
(153,1,'highly_recommended','label','both','Highly recommended if specific  extinguishing media are required or appropriate'),
(154,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(154,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(155,1,'highly_recommended','label','both','Highly recommended '),
(156,1,'highly_recommended','label','both','Highly recommended where the  packaging is important for preventing or suppressing the effect of dangerous reactions or explosion'),
(157,1,'optional','label','both','Optional '),
(158,1,'highly_recommended','label','both','Highly recommended '),
(159,1,'highly_recommended','label','both','Highly recommended, in  combination with P411 or P235'),
(160,1,'optional','label','both','Optional if P411 or P235 has  already been assigned'),
(162,1,'recommended','label','both','Recommended for inclusion  in the safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(163,1,'optional','label','both','Optional unless other conditions  deem it necessary'),
(163,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(164,1,'highly_recommended','label','both','Highly recommended '),
(165,1,'recommended','label','both','Recommended where incompatible  materials are likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information'),
(166,1,'highly_recommended','label','both','Highly recommended '),
(167,1,'highly_recommended','label','both','Highly recommended '),
(168,1,'optional','label','both','Optional '),
(170,1,'highly_recommended','label','both','Highly recommended, in  combination with P411 or P235'),
(171,1,'optional','label','both','Optional if P411 or P235 has  already been assigned'),
(173,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(173,2,'recommended','label','both','Recommended for  inclusion in the safety data'),
(174,1,'highly_recommended','label','both','Highly recommended '),
(175,1,'recommended','label','both','Recommended where  incompatible materials are likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information'),
(176,1,'highly_recommended','label','both','Highly recommended '),
(177,1,'highly_recommended','label','both','Highly recommended '),
(178,1,'optional','label','both','Optional '),
(179,1,'highly_recommended','label','both','Highly recommended if  specific extinguishing media are required or appropriate'),
(180,1,'highly_recommended','label','both','Highly recommended, in combination  with P411 or P235'),
(181,1,'optional','label','both','Optional if P411 or P235 has already  been assigned'),
(183,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(183,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(184,1,'optional','label','both','Optional unless other conditions  deem it necessary'),
(184,2,'recommended','label','both','Recommended for inclusion in  the safety data sheet'),
(185,1,'highly_recommended','label','both','Highly recommended '),
(186,1,'recommended','label','both','Recommended where incompatible  materials are likely to produce a particular risk. If this statement is used, text clarifying the incompatible materials should be added as supplemental information'),
(187,1,'recommended','label','general_public','Recommended for the general public '),
(187,2,'optional','label','professional','Optional for industrial / professional  users'),
(187,3,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(188,1,'recommended','label','both','Recommended '),
(189,1,'optional','label','both','Optional  Do not use if P234 has already been  assigned'),
(190,1,'highly_recommended','label','general_public','Highly recommended for the  general public'),
(190,2,'recommended','label','professional','Recommended for industrial /  professional users'),
(191,1,'highly_recommended','label','general_public','Highly recommended for the  general public for categories 1 and 2'),
(192,1,'highly_recommended','label','both','Highly recommended '),
(194,1,'highly_recommended','label','general_public','Highly recommended for  the general public'),
(194,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(195,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(195,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements'),
(196,1,'recommended','label','both','Recommended '),
(197,1,'recommended','label','general_public','Recommended for the general public '),
(197,2,'optional','label','professional','Optional for industrial / professional  users'),
(197,3,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(198,1,'optional','label','both','Optional '),
(199,1,'optional','label','both','Optional '),
(200,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(200,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(200,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(201,1,'highly_recommended','label','both','Highly recommended '),
(202,1,'highly_recommended','label','both','Highly recommended '),
(203,1,'highly_recommended','label','both','Highly recommended for the general  public'),
(203,2,'optional','label','professional','Optional for industrial / professional  users.'),
(203,3,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(204,1,'recommended','label','both','Recommended for the general  public'),
(204,2,'recommended','label','both','Recommended for inclusion in  the safety data sheet'),
(205,1,'highly_recommended','label','both','Highly recommended, in  combination with P302+P352'),
(206,1,'highly_recommended','label','general_public','Highly recommended for  the general public'),
(206,2,'optional','label','professional','Optional for  industrial/professional users unless other conditions (Member State legislation) deem it necessary'),
(207,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(207,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet if there are specific disposal requirements above the normal expectation for the disposal of chemicals. Specify the applicable regulation.'),
(208,1,'highly_recommended','label','both','Highly recommended '),
(209,1,'highly_recommended','label','both','Highly recommended only in  exceptional cases where specific treatment is known and required'),
(210,1,'recommended','label','both','Recommended '),
(211,1,'highly_recommended','label','both','Highly recommended '),
(212,1,'recommended','label','both','Recommended for the general  public'),
(212,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(213,1,'recommended','label','both','Recommended '),
(214,1,'highly_recommended','label','general_public','Highly recommended for  the general public'),
(214,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(215,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(215,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(215,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(216,1,'highly_recommended','label','both','Highly recommended only in  exceptional cases where specific treatment is known and required'),
(217,1,'recommended','label','both','Recommended '),
(218,1,'recommended','label','both','Recommended '),
(219,1,'optional','label','both','Optional '),
(220,1,'recommended','label','both','Recommended '),
(221,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(221,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(221,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(222,1,'highly_recommended','label','both','Highly recommended only in  exceptional cases where specific treatment is known and required'),
(223,1,'optional','label','both','Optional '),
(224,1,'highly_recommended','label','both','Highly recommended '),
(225,1,'highly_recommended','label','general_public','Highly recommended for the  general public'),
(225,2,'optional','label','professional','Optional for  industrial/professional users'),
(226,1,'highly_recommended','label','both','Highly recommended '),
(227,1,'highly_recommended','label','both','Highly recommended, in  combination with P304+P340'),
(228,1,'highly_recommended','label','both','Highly recommended unless  P404 has already been assigned'),
(229,1,'highly_recommended','label','general_public','Highly recommended for the  general public'),
(229,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(230,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(230,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(230,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(231,1,'recommended','label','professional','Recommended for  industrial/professional users in exceptional cases where inadequate ventilation/organisational measures cannot sufficiently prevent inhalation'),
(231,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(232,1,'highly_recommended','label','both','Highly recommended only in  exceptional cases where specific treatment is known and required'),
(233,1,'recommended','label','both','Recommended '),
(234,1,'highly_recommended','label','general_public','Highly recommended for the  general public'),
(234,2,'optional','label','professional','Optional for  industrial/professional users'),
(235,1,'recommended','label','both','Recommended '),
(236,1,'recommended','label','both','Recommended, in combination with '),
(238,1,'highly_recommended','label','both','Highly recommended only in exceptional  cases where specific treatment is known and required'),
(239,1,'highly_recommended','label','both','Highly recommended '),
(240,1,'highly_recommended','label','general_public','Highly recommended for  the general public'),
(240,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(241,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(241,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(241,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(242,1,'recommended','label','both','Recommended '),
(243,1,'highly_recommended','label','both','Highly recommended for the general  public'),
(243,2,'optional','label','professional','Optional for industrial/professional  users'),
(244,1,'optional','label','both','Optional '),
(245,1,'recommended','label','both','Recommended '),
(246,1,'highly_recommended','label','both','Highly recommended '),
(247,1,'highly_recommended','label','both','Highly recommended for the general  public, unless P280 has already been assigned'),
(248,1,'highly_recommended','label','both','Highly recommended for the general  public, provided that medical advice indicates that the statement is appropriate'),
(248,2,'recommended','label','professional','Recommended for industrial /  professional users, provided that medical advice indicates that the statement is appropriate'),
(250,1,'highly_recommended','label','general_public','Highly recommended for  the general public'),
(250,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(251,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(251,2,'recommended','label','professional','Recommended for industrial  / professional users if there'),
(252,1,'highly_recommended','label','both','Highly recommended '),
(253,1,'recommended','label','general_public','Recommended for the general public '),
(253,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(254,1,'optional','label','both','Optional '),
(255,1,'highly_recommended','label','both','Highly recommended, in  combination with P303+P361+P353, P305+P351+ P338 or P301 + P330 + P331'),
(257,1,'highly_recommended','label','both','Highly recommended '),
(258,1,'recommended','label','both','Recommended '),
(259,1,'recommended','label','both','Recommended '),
(260,1,'optional','label','general_public','Optional for the general public '),
(260,2,'recommended','label','both','Recommended for inclusion in the safety data  sheet'),
(261,1,'recommended','label','both','Recommended only in exceptional cases where  specific treatment is known and required'),
(262,1,'optional','label','both','Optional '),
(263,1,'optional','label','both','Optional '),
(263,2,'recommended','label','both','Recommended for inclusion in the safety data  sheet'),
(264,1,'highly_recommended','label','both','Highly recommended  Where a chemical is classified as skin corrosion 52 is already included in the hazard statement for skin'),
(265,1,'highly_recommended','label','both','Highly recommended '),
(266,1,'highly_recommended','label','both','Highly recommended, in combination  with P305+P351+P338 Sub-Category 1A, 1B, 1C or Category 1, labelling for corrosion Category 1 (H314).'),
(267,1,'optional','label','professional','Optional for the industrial/ professional users '),
(267,2,'recommended','label','general_public','Recommended for the general public '),
(268,1,'recommended','label','both','Recommended  Where a chemical is classified as skin corrosion Sub-Category 1A, 53 is already included in the hazard statement for skin corrosion Category'),
(269,1,'recommended','label','both','Recommended for the general  public'),
(269,2,'recommended','label','both','Recommended for inclusion in  the safety data sheet') on conflict do nothing;

insert into echa_p_recommendation (block_id, seq, level, scope, audience, condition_text) values
(270,1,'recommended','label','both','Recommended  1B, 1C or Category 1, labelling for serious 1 (H314).'),
(271,1,'highly_recommended','label','both','Highly recommended '),
(272,1,'recommended','label','professional','Recommended for industrial/professional users in  exceptional cases where inadequate ventilation/organisational measures cannot sufficiently prevent inhalation'),
(272,2,'recommended','label','both','Recommended for inclusion in the safety data  sheet'),
(273,1,'highly_recommended','label','both','Highly recommended '),
(274,1,'highly_recommended','label','both','Highly recommended '),
(275,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(275,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(275,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(276,1,'recommended','label','both','Recommended '),
(277,1,'optional','label','professional','Optional for industrial/professional users '),
(278,1,'recommended','label','both','Recommended for the general  public'),
(278,2,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(279,1,'recommended','label','both','Recommended '),
(280,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(280,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(280,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(281,1,'highly_recommended','label','both','Highly recommended '),
(282,1,'highly_recommended','label','both','Highly recommended only in  exceptional cases where specific treatment is known and required'),
(283,1,'recommended','label','both','Recommended '),
(284,1,'highly_recommended','label','both','Highly recommended for category 1A  and 1B'),
(284,2,'recommended','label','both','Recommended for category 2 '),
(285,1,'optional','label','professional','Optional where P201 is assigned  54 Substances and mixtures which are listed in H350 or H360 are restricted to industrial / professional REACH, as amended). The list of subsequent'),
(286,1,'highly_recommended','label','both','Highly recommended for  category 1A and 1B'),
(286,2,'recommended','label','both','Recommended for category 2  Appendix 1-6 of Annex XVII to Regulation users and normally not supplied amendments of Annex XVII is accessible'),
(287,1,'highly_recommended','label','general_public','Highly recommended for the  general public 54'),
(287,2,'optional','label','general_public','Optional for  industrial/professional users unless other conditions (Member State legislation) deem it necessary (EC) No 1907/2006 (REACH) to the general public (see entry at http://echa.europa.eu/web/guest/regulations/reach/legislation.'),
(288,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not and which are assigned H340, 28, 29 and 30 in Annex XVII to'),
(289,1,'highly_recommended','label','both','Highly recommended '),
(290,1,'highly_recommended','label','both','Highly recommended for category  1A and 1B'),
(290,2,'recommended','label','both','Recommended for category 2 '),
(291,1,'optional','label','professional','Optional where P201 is assigned  55 Substances and mixtures which are listed or H360 are restricted to industrial / professional as amended). The list of subsequent amendments'),
(292,1,'highly_recommended','label','both','Highly recommended for  category 1A and 1B'),
(292,2,'recommended','label','both','Recommended for category  2 in Appendix 1-6 of Annex XVII to Regulation users and normally not supplied of Annex XVII is accessible'),
(293,1,'highly_recommended','label','general_public','Highly recommended for the  general public 55'),
(293,2,'optional','label','general_public','Optional for  industrial/professional users unless other conditions (Member State legislation) deem it necessary (EC) No 1907/2006 (REACH) to the general public (see entry at: http://echa.europa.eu/web/guest/regulations/reach/legislation.'),
(294,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary. and which are assigned H340, H350 28, 29 and 30 in Annex XVII to REACH'),
(295,1,'highly_recommended','label','both','Highly recommended '),
(296,1,'highly_recommended','label','both','Highly recommended for  category 1A and 1B'),
(296,2,'recommended','label','both','Recommended for category 2 '),
(298,1,'highly_recommended','label','both','Highly recommended for  category 1A and 1B'),
(298,2,'recommended','label','professional','Recommended for category 2  in Appendix 1-6 of Annex XVII to / professional users and normally not amendments of Annex XVII is accessible'),
(299,1,'highly_recommended','label','general_public','Highly recommended  for the general public 56'),
(299,2,'optional','label','general_public','Optional for  industrial / professional users unless other conditions (Member State legislation) deem it necessary Regulation (EC) No 1907/2006 supplied to the general public at ECHA website:'),
(300,1,'recommended','label','both','recommended to specify the site of disposal while a reference (REACH) and which are assigned H340, (see entry 28, 29 and 30 in Annex XVII to'),
(301,1,'highly_recommended','label','both','Highly recommended '),
(302,1,'highly_recommended','label','both','Highly recommended '),
(303,1,'highly_recommended','label','both','Highly recommended '),
(304,1,'highly_recommended','label','both','Highly recommended '),
(305,1,'recommended','label','both','Recommended '),
(306,1,'optional','label','both','Optional '),
(307,1,'recommended','label','general_public','Recommended for the general public '),
(307,2,'optional','label','professional','Optional for industrial / professional users '),
(307,3,'recommended','label','both','Recommended for inclusion in the safety  data sheet'),
(308,1,'highly_recommended','label','both','Highly recommended where the  substance / mixture is volatile or a gas or where exposure via inhalation is possible, e.g. through spraying or inhalable dust or in case H370 indicates inhalation as a route of exposure'),
(309,1,'optional','label','both','Optional '),
(310,1,'highly_recommended','label','both','Highly recommended '),
(311,1,'highly_recommended','label','both','Highly recommended only in  exceptional cases where specific treatment is known and required'),
(312,1,'highly_recommended','label','general_public','Highly recommended for  the general public'),
(312,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(313,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(313,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(313,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(314,1,'recommended','label','both','Recommended for the general  public'),
(314,2,'optional','label','professional','Optional for industrial / professional  users'),
(314,3,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(315,1,'highly_recommended','label','both','Highly recommended where the  substance / mixture is volatile or a gas or where exposure via inhalation is possible, e.g. through spraying or inhalable dust or in case H371 indicates inhalation as a route of exposure'),
(316,1,'optional','label','both','Optional '),
(317,1,'recommended','label','both','Recommended '),
(318,1,'highly_recommended','label','general_public','Highly recommended for  the general public'),
(318,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(319,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(319,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(319,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation'),
(320,1,'recommended','label','both','Recommended for the general  public'),
(320,2,'optional','label','professional','Optional for industrial / professional  users'),
(320,3,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(321,1,'recommended','label','both','Recommended '),
(322,1,'highly_recommended','label','general_public','Highly recommended for the  general public'),
(322,2,'optional','label','professional','Optional for industrial /  professional users'),
(323,1,'optional','label','both','Optional '),
(324,1,'recommended','label','both','Recommended '),
(325,1,'recommended','label','both','Recommended unless P404 is  assigned'),
(326,1,'highly_recommended','label','general_public','Highly recommended for the  general public'),
(326,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(327,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(327,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(327,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(328,1,'highly_recommended','label','both','Highly recommended where the  substance / mixture is volatile or a gas or where exposure via inhalation is possible, e.g. through spraying or inhalable dust or in case H372 indicates inhalation as a route of exposure'),
(329,1,'optional','label','both','Optional '),
(330,1,'recommended','label','both','Recommended '),
(331,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(331,2,'recommended','label','professional','Recommended for industrial / professional  users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(331,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(332,1,'recommended','label','general_public','Recommended for the general public '),
(332,2,'optional','label','professional','Optional for industrial / professional  users'),
(332,3,'recommended','label','both','Recommended for inclusion in the  safety data sheet'),
(333,1,'highly_recommended','label','both','Highly recommended where the  substance / mixture is highly volatile or a gas or where exposure via inhalation is possible, e.g. through spraying or inhalable dust or in case H373 indicates inhalation as a route of exposure'),
(334,1,'recommended','label','both','Recommended '),
(335,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(335,2,'recommended','label','professional','Recommended for industrial /  professional users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(335,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(336,1,'highly_recommended','label','both','Highly recommended, in  combination with P331'),
(337,1,'highly_recommended','label','both','Highly recommended, in  combination with P301 +P310'),
(338,1,'highly_recommended','label','general_public','Highly recommended for the  general public'),
(338,2,'optional','label','professional','Optional for industrial /  professional users unless other conditions (Member State legislation) deem it necessary'),
(339,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(339,2,'recommended','label','professional','Recommended for industrial / professional  users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(339,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(340,1,'highly_recommended','label','both','Highly recommended '),
(341,1,'highly_recommended','label','both','Highly recommended '),
(342,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(342,2,'recommended','label','professional','Recommended for industrial / professional  users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(342,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(343,1,'highly_recommended','label','both','Highly recommended '),
(344,1,'highly_recommended','label','both','Highly recommended '),
(345,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(345,2,'recommended','label','professional','Recommended for industrial / professional  users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(345,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(346,1,'recommended','label','both','Recommended '),
(347,1,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(347,2,'recommended','label','professional','Recommended for industrial / professional  users if there are specific disposal requirements above the normal expectation for the disposal of chemicals. It is'),
(347,3,'recommended','label','both','recommended to specify the site of disposal while a reference to the applicable legislation is not necessary.'),
(348,1,'highly_recommended','label','professional','Highly recommended for industrial /  professional users') on conflict do nothing;
